### PR TITLE
Make resource validation fail-fast safety

### LINKED ISSUE #3780: Resource validation steps don't work correctly with scenario fail-fast
**Describe the bug**
Resource validation steps don't work correctly with scenario fail-fast.
Steps (can be more):
`Then HTTP resources are valid:$resources`
``Then all resources by selector `$cssSelector` are valid on:$pages``

Defects:
1. Steps make validation until the first broken resource (first failed assertion, but even with fail-fast step must check all resources);
2. Step ``Then all resources by selector `$cssSelector` are valid on:$pages`` become broken;
3. All steps lose their attachments.

**To Reproduce**
Enable scenario fail-fast:
`scenario.fail-fast=true`
Run steps above over any site with invalid checking resources.

**Expected behavior**
Resource validation steps have to work correctly with enabled scenario fail-fast.
1. Steps have to validate all resources regardless of their statuses;
2. No broken steps;
3. All steps must to have their attachments (resource validation tables).

**Artifacts**
[allureBrokenChecker.zip](https://github.com/vividus-framework/vividus/files/11089532/allureBrokenChecker.zip)
[ResourceCheckersStory.zip](https://github.com/vividus-framework/vividus/files/11089541/ResourceCheckersStory.zip)
* Note that the stories above used a local site with predefined broken pages.

### PR DESCRIPTION
**Pull request by draker94**
Closes #3780

### CODE REVIEW

File: vividus-plugin-rest-api/src/main/java/org/vividus/http/validation/ResourceValidator.java [hunk 1]
```diff
@@ -104,4 +104,9 @@ private HttpResponse executeHttpMethod(HttpMethod httpMethod, HttpClientContext
         ClassicHttpRequest request = httpMethod.createRequest(uri);
         return httpClient.execute(request, httpClientContext);
     }
+
+    public void clearCache()
```
Comment (valfirst) [inline vividus-plugin-rest-api/src/main/java/org/vividus/http/validation/ResourceValidator.java:108]: why is it needed?

File: vividus-soft-assert/build.gradle [hunk 2]
```diff
@@ -4,6 +4,7 @@ dependencies {
     api(group: 'org.hamcrest', name: 'hamcrest', version: '2.2')
 
     implementation project(':vividus-test-context')
+    implementation(group: 'org.apache.commons', name: 'commons-lang3', version: '3.12.0')
```
Comment (valfirst) [inline vividus-soft-assert/build.gradle:7]: it's better to create own simple interface instead of adding extra dependencies to low-level modules

File: vividus-soft-assert/src/main/java/org/vividus/softassert/FailTestFastManager.java [hunk 3]
```diff
@@ -19,4 +19,6 @@
 public interface FailTestFastManager
 {
     boolean isFailTestCaseFast();
+
+    void setFailTestCaseFast(boolean failTestCaseFast);
```
Comment (valfirst) [inline vividus-soft-assert/src/main/java/org/vividus/softassert/FailTestFastManager.java:23]:
```suggestion
    boolean isTestCaseFailFastEnabled();

    void enableTestCaseFailFast();

    void disableTestCaseFailFast();
```

File: vividus-soft-assert/src/main/java/org/vividus/softassert/ISoftAssert.java [hunk 4]
```diff
@@ -246,4 +247,13 @@
...
     void verify(Pattern pattern) throws VerificationError;
+
+    /**
+     * Disable fail-fast at scenario level and run <code>FailableRunnable</code> operation.
+     * After the operation is completed fail-fast settings are restored.
+     * @param runnable FailableRunnable operation
+     * @param <E> Thrown when the operation fails
+     * @throws Exception If an exception occurs during execution of the operation
+     */
+    <E extends Exception> void runOperationIgnoreTestFailFast(FailableRunnable<E> runnable) throws E;
```
Comment (valfirst) [inline vividus-soft-assert/src/main/java/org/vividus/softassert/ISoftAssert.java:258]: it seems Supplier fits better here

File: vividus-soft-assert/src/main/java/org/vividus/softassert/SoftAssert.java [hunk 5]
```diff
@@ -440,6 +465,11 @@ private AssertionCollection getAssertionCollection()
         return testContext.get(AssertionCollection.class, AssertionCollection::new);
     }
 
+    private FailTestFastManager getFailTestFastManager()
+    {
+        return testContext.get(FailTestFastManager.class, failTestFastManagerFactory::createFailTestFastManager);
```
Comment (valfirst) [inline vividus-soft-assert/src/main/java/org/vividus/softassert/SoftAssert.java:470]: why is it needed to create own manager for each thread?

**Review by valfirst — CHANGES_REQUESTED** [review]

File: vividus-plugin-rest-api/src/main/java/org/vividus/http/validation/ResourceValidator.java (hunk 1 above)
Comment (draker94) [reply vividus-plugin-rest-api/src/main/java/org/vividus/http/validation/ResourceValidator.java:108]: [Validator](https://github.com/vividus-framework/vividus/blob/99df3bbcf5a008c58969af4d12376398b8e27edb/vividus-plugin-rest-api/src/main/java/org/vividus/http/validation/ResourceValidator.java#L52) cache can store or [WebPageResourceValidation](https://github.com/vividus-framework/vividus/blob/ada61576f8f8ddec1c951dd50bcfd1d3c7a45a4e/vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/validator/model/WebPageResourceValidation.java) or [ResourceValidation](https://github.com/vividus-framework/vividus/blob/ada61576f8f8ddec1c951dd50bcfd1d3c7a45a4e/vividus-plugin-rest-api/src/main/java/org/vividus/http/validation/model/ResourceValidation.java) (for different validation steps) and if we're using different steps for validation cached result from one step may be used in another step with class cast exception.

File: vividus-soft-assert/src/main/java/org/vividus/softassert/SoftAssert.java (hunk 5 above)
Comment (draker94) [reply vividus-soft-assert/src/main/java/org/vividus/softassert/SoftAssert.java:470]: If we setup two or more cores for test run we accordingly can have two or more stories which are running parallel. And if story with resource validation changing singleton manager, other stories can "lose" correct predefined fail-fast value

File: vividus-plugin-rest-api/src/main/java/org/vividus/steps/http/HttpResourceValidationSteps.java [hunk 6]
```diff
@@ -23,20 +23,24 @@
...
 
 public class HttpResourceValidationSteps
 {
     private final ResourceValidator<ResourceValidation> resourceValidator;
     private final AttachmentPublisher attachmentPublisher;
+    private final ISoftAssert softAssert;
 
     public HttpResourceValidationSteps(ResourceValidator<ResourceValidation> resourceValidator,
-            AttachmentPublisher attachmentPublisher)
+            AttachmentPublisher attachmentPublisher, ISoftAssert softAssert)
```
Comment (valfirst) [inline vividus-plugin-rest-api/src/main/java/org/vividus/steps/http/HttpResourceValidationSteps.java:39]:
```suggestion
            ISoftAssert softAssert, AttachmentPublisher attachmentPublisher)
```

File: vividus-plugin-rest-api/src/main/java/org/vividus/steps/http/HttpResourceValidationSteps.java [hunk 7]
```diff
@@ -51,16 +55,29 @@ public HttpResourceValidationSteps(ResourceValidator<ResourceValidation> resourc
...
+
+    private void checkValidations(List<ResourceValidation> validations)
+    {
+        for (ResourceValidation resource : validations)
+        {
+            if (resource.getCheckStatus() == CheckStatus.FAILED || resource.getCheckStatus() == CheckStatus.BROKEN)
+            {
+                softAssert.recordFailedAssertion("Found broken resources or resources with invalid status codes!");
+                return;
+            }
```
Comment (valfirst) [inline vividus-plugin-rest-api/src/main/java/org/vividus/steps/http/HttpResourceValidationSteps.java:80]: why do we need it? to trigger fail-fast action?

File: vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/steps/integration/ResourceCheckSteps.java [hunk 8]
```diff
@@ -96,37 +98,43 @@ public void init()
      *     3. If element doesn't contain href or src attribute fail assertion will be recorded
      * @param cssSelector to locate resources
      * @param html to validate
-     * @throws InterruptedException when a thread is interrupted
-     * @throws ExecutionException  when exception thrown before result get
+     * @throws Exception when exception occurred
      */
     @Then("all resources by selector `$cssSelector` from $html are valid")
-    public void checkResources(String cssSelector, String html) throws InterruptedException, ExecutionException
+    public void checkResources(String cssSelector, String html) throws Exception
```
Comment (valfirst) [inline vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/steps/integration/ResourceCheckSteps.java:104]: it's better to keep all exception instead of just `Exception`

File: vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/steps/integration/ResourceCheckSteps.java [hunk 9]
```diff
@@ -335,4 +347,21 @@ public void setUriToIgnoreRegex(Optional<String> uriToIgnoreRegex)
...
+                return true;
+            }
+        }
+        return false;
+    }
+
+    private void recordFailedResourcesValidation()
+    {
+        softAssert.recordFailedAssertion("Found broken resources or resources with invalid status codes!");
+    }
```
Comment (valfirst) [inline vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/steps/integration/ResourceCheckSteps.java:366]: the same question: why do we need it? to trigger fail-fast action?

File: vividus-soft-assert/src/main/java/org/vividus/softassert/ISoftAssert.java [hunk 10]
```diff
@@ -246,4 +246,15 @@
...
+    /**
+     * Disable fail-fast at the test case level and return result of <code>SoftAssertFailableSupplier</code> operation.
+     * After the operation is completed fail-fast settings are restored.
+     * @param <R> The type of value to return
+     * @param <E> Throws if an exception occurred during execution of the operation
+     * @param supplier SoftAssertFailableSupplier operation
+     * @return Result of the operation
+     * @throws E If an exception occurred during execution of the operation
+     */
+    <R, E extends Exception> R runOperationIgnoreTestFailFast(SoftAssertFailableSupplier<R, E> supplier) throws E;
```
Comment (valfirst) [inline vividus-soft-assert/src/main/java/org/vividus/softassert/ISoftAssert.java:259]:
```suggestion
    <R, E extends Exception> R runIgnoringTestFailFast(SoftAssertFailableSupplier<R, E> supplier) throws E;
```

File: vividus-soft-assert/src/main/java/org/vividus/softassert/SoftAssertFailableSupplier.java [hunk 11]
```diff
@@ -0,0 +1,23 @@
...
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+package org.vividus.softassert;
+
+@FunctionalInterface
+public interface SoftAssertFailableSupplier<R, E extends Exception>
```
Comment (valfirst) [inline vividus-soft-assert/src/main/java/org/vividus/softassert/SoftAssertFailableSupplier.java:20]:
```suggestion
public interface FailableSupplier<R, E extends Exception>
```
name can be generic here

**Review by valfirst — CHANGES_REQUESTED** [review]

File: vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/steps/integration/ResourceCheckSteps.java (hunk 9 above)
Comment (draker94) [reply vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/steps/integration/ResourceCheckSteps.java:366]: > the same question: why do we need it? to trigger fail-fast action?

Yes
I also think about to use `AssertionFailedEvent` but it's seems not thread safety.

File: vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/steps/integration/ResourceCheckSteps.java (hunk 8 above)
Comment (draker94) [reply vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/steps/integration/ResourceCheckSteps.java:104]: > it's better to keep all exception instead of just `Exception`

Do you mean just left subclass exceptions (`InterruptedException`, `ExecutionException`) in method signature and javadocs?

File: vividus-soft-assert/src/main/java/org/vividus/softassert/SoftAssert.java [hunk 12]
```diff
@@ -317,6 +318,29 @@ public void verify(Pattern pattern) throws VerificationError
         verify();
     }
 
+    @Override
+    public <E extends Exception> void runIgnoringTestFailFast(FailableRunnable<E> runnable) throws E
+    {
+        boolean testCaseFailFast = isFailTestCaseFast();
+        if (testCaseFailFast)
+        {
+            testContext.put(FAIL_TEST_CASE_FAST_KEY, false);
```
Comment (valfirst) [inline vividus-soft-assert/src/main/java/org/vividus/softassert/SoftAssert.java:327]: this flag should be managed in `failTestFastManager`

File: vividus-soft-assert/src/main/java/org/vividus/softassert/FailTestFastManager.java [hunk 13]
```diff
@@ -18,5 +18,9 @@
 
 public interface FailTestFastManager
 {
-    boolean isFailTestCaseFast();
+    boolean isTestCaseFailFastEnabled();
```
Comment (valfirst) [inline vividus-soft-assert/src/main/java/org/vividus/softassert/FailTestFastManager.java:21]: I think old name can be preserved, I don't see any contradiction

File: vividus/src/main/java/org/vividus/softassert/JBehaveFailTestFastManager.java [hunk 14]
```diff
@@ -21,26 +21,44 @@
 import org.vividus.batch.BatchConfiguration;
 import org.vividus.batch.BatchStorage;
 import org.vividus.context.RunContext;
+import org.vividus.testcontext.TestContext;
 
 public class JBehaveFailTestFastManager implements FailTestFastManager
 {
+    private static final String FAIL_TEST_CASE_FAST_KEY = "FailTestCaseFast";
```
Comment (valfirst) [inline vividus/src/main/java/org/vividus/softassert/JBehaveFailTestFastManager.java:28]: it's better to use some unique key to be sure that no one else will use the same key, general rule is:
```suggestion
    private static final Object FAIL_TEST_CASE_FAST_KEY = JBehaveFailTestFastManager.class;
```

**Review by valfirst — CHANGES_REQUESTED** [review]

File: vividus-soft-assert/src/main/java/org/vividus/softassert/FailableRunnable.java [hunk 15]
```diff
@@ -0,0 +1,23 @@
...
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+package org.vividus.softassert;
+
+@FunctionalInterface
+public interface FailableRunnable<E extends Exception>
```
Comment (uarlouski) [inline vividus-soft-assert/src/main/java/org/vividus/softassert/FailableRunnable.java:20]: why not org.apache.commons.lang3.function.FailableRunnable?

**Review by uarlouski — APPROVED** [review]

File: vividus-soft-assert/src/main/java/org/vividus/softassert/FailableRunnable.java (hunk 15 above)
Comment (valfirst) [reply vividus-soft-assert/src/main/java/org/vividus/softassert/FailableRunnable.java:20]: to avoid extra dependency in so small module

**Review by valfirst — APPROVED** [review]
