### PR TITLE
[bdd-engine] Resolve variables as part of names of another variables

### LINKED ISSUE #1181: Composite variables are not resolving
Scenario should pass:
```
When I initialize the SCENARIO variable `variable` with value `Variable`
When I initialize the SCENARIO variable `compositeVariable` with value `expected result`
Then `${composite${variable}}` is = `expected result`
```
Actual result:
```
 Fail: Checking if "${composite${variable}}" is equal to "expected result" [Expected: "expected result" Actual: was "${composite${variable}}"]
```

### PR DESCRIPTION
**Pull request by valfirst**
Fixes #1181

### CODE REVIEW

**Review by ikalinin1 — APPROVED** [review]

File: vividus-bdd-engine/src/main/java/org/vividus/bdd/steps/ParameterAdaptor.java [hunk 1]
```diff
@@ -28,7 +28,7 @@
 
 public class ParameterAdaptor
 {
-    private static final Pattern DYNAMIC_DATA_PATTERN = Pattern.compile("\\$\\{(((?!\\$|\\#).|(?<=:).)*?}*)}");
+    private static final Pattern DYNAMIC_DATA_PATTERN = Pattern.compile("\\$\\{(((?![$#]).)*?(:.+)?)}");
```
Comment (uarlouski) [inline vividus-bdd-engine/src/main/java/org/vividus/bdd/steps/ParameterAdaptor.java:31]: third group never used in code, let's make it non-capturing?

**Review by uarlouski — APPROVED** [review]

**Review by abudevich — APPROVED** [review]

**Review by ikalinin1 — APPROVED** [review]
