### PR TITLE
[engine] Trim whitespaces in the resource patterns

### LINKED ISSUE #2688: White spaces not trimmed in include pattern properties
Steps to reproduce:
1. Put a space after the story name.
```
bdd.story-loader.batch-1.resource-include-patterns=Sample.story 
```

Actual results:
Story not found, no tests were executed

Expected results:
Story found, tests are executed

### PR DESCRIPTION
**Pull request by ikalinin1**
fixes #2688

### CODE REVIEW

File: vividus-engine/src/main/java/org/vividus/batch/BatchResourceConfiguration.java [hunk 1]
```diff
@@ -63,6 +65,8 @@ private List<String> convertToList(String list)
         {
             return List.of();
         }
-        return List.of(StringUtils.split(list, ','));
+        return Stream.of(StringUtils.split(list, ','))
+                     .map(String::strip)
+                     .collect(Collectors.toList());
```
Comment (valfirst) [inline vividus-engine/src/main/java/org/vividus/batch/BatchResourceConfiguration.java:70]: Does it make sense to update the docs as well?

File: vividus-tests/src/main/resources/properties/suite/failFast/suite.properties [hunk 2]
```diff
@@ -1,8 +1,8 @@
 bdd.story-loader.batch-1.resource-location=story/integration/failFast
-bdd.story-loader.batch-1.resource-include-patterns=FailFast*.story,Success.story
+bdd.story-loader.batch-1.resource-include-patterns=FailFast*.story ,Success.story
 bdd.batch-1.threads=2
 bdd.story-loader.batch-2.resource-location=story/integration/failFast
-bdd.story-loader.batch-2.resource-include-patterns=Should not be executed.story
+bdd.story-loader.batch-2.resource-include-patterns= Should not be executed.story
```
Comment (valfirst) [inline vividus-tests/src/main/resources/properties/suite/failFast/suite.properties:5]: it seems this batch shouldn't be executed, so it's not a good place to put spaces

**Review by valfirst — CHANGES_REQUESTED** [review]

**Review by uarlouski — APPROVED** [review]

**Review by abudevich — APPROVED** [review]

**Review by valfirst — APPROVED** [review]
