### PR TITLE
[bdd-engine] Fix variables resolution for the values with preceding `}`

### LINKED ISSUE #1252: Invalid result is returned after applying regular expression
```gherkin
Scenario: test1
When I initialize the STORY variable `dbSapp` with value `[{BNS_TRX_ID=4}, {BNS_TRX_ID=4}, {BNS_TRX_ID=4}, {BNS_TRX_ID=4}]`
When I initialize the STORY variable `BnsCustID` with value `#{replaceAllByRegExp("""\},\s\{BNS_TRX_ID=""", """,""", """${dbSapp}""")}`
Then `${BnsCustID}` is = `[{BNS_TRX_ID=4,4,4,4}]`

Scenario: test2
When I initialize the STORY variable `dbSapp` with value `[{CUST_SPON_ID=1}]`
When I initialize the STORY variable `BnsCustID` with value `#{replaceAllByRegExp(.\{CUST_SPON_ID=(\d+)\}?]?, $1, """${dbSapp}""")}`
Then `${BnsCustID}` is = `1`

Scenario: test3
When I initialize the STORY variable `dbSapp` with value `[{PROC_STAT_CD=cp, RTURN_CD=pr}]`
When I initialize the STORY variable `BnsCustID` with value `#{replaceFirstByRegExp(.*RTURN_CD=(.*)\}.*, $1, """${dbSapp}""")}`
Then `${BnsCustID}` is = `pr`
```

**Expected behavior**
Then steps are passed, regular expressions works as expected

**Artifacts**
If applicable, add artifacts to help explain your problem:
[regexissue.log](https://github.com/vividus-framework/vividus/files/5714871/regexissue.log)

**Execution environment (please complete the following information):**
vividus: 0.2.13-SNAPSHOT

**Note:** issue isn't reproducible on vividus: 0.2.10

### PR DESCRIPTION
**Pull request by ikalinin1**
Fixes #1252

### CODE REVIEW

File: vividus-bdd-engine/src/test/java/org/vividus/bdd/steps/VariableResolverTests.java [hunk 1]
```diff
@@ -61,11 +61,13 @@ private Object convert(String value)
...
             " '{\"ids\": [\"${var}\", \"12-ce\"]}', var,             value, '{\"ids\": [\"value\", \"12-ce\"]}'",
-            " ${var${varPartName}},                 varPartName,     value, ${varvalue}"
+            " ${var${varPartName}},                 varPartName,     value, ${varvalue}",
+            " '#{exp(\\}{BNS_TRX_ID=, A, ${var})}', var,             value, '#{exp(\\}{BNS_TRX_ID=, A, value)}'",
+            " [JAVA_HOME=].*[^${PATH}].*,           var,             value, [JAVA_HOME=].*[^${PATH}].*"
     })
     void shouldResolveVariables(String valueToResolve, String variableKey, String variableValue, String expected)
     {
-        when(bddVariableContext.getVariable(variableKey)).thenReturn(variableValue);
+        lenient().when(bddVariableContext.getVariable(variableKey)).thenReturn(variableValue);
```
Comment (valfirst) [inline vividus-bdd-engine/src/test/java/org/vividus/bdd/steps/VariableResolverTests.java:70]: why is `lenient` required now?

Comment (ikalinin1) [reply vividus-bdd-engine/src/test/java/org/vividus/bdd/steps/VariableResolverTests.java:70]: Because there is an unnecessary mocking for the last example, but I feel it is better to keep all the cases in one place

Comment (valfirst) [reply vividus-bdd-engine/src/test/java/org/vividus/bdd/steps/VariableResolverTests.java:70]: in this case the last value can be moved to `shouldReturnTheSameValueWhenNothingToResolve `

**Review by valfirst — APPROVED** [review]

**Review by uarlouski — APPROVED** [review]
