### PR TITLE
[vividus-extension-selenium] Fix regex for locator converter

### LINKED ISSUE #1993: Illegal visibility type for "When I find ... elements by ... and for each element do..." step with cssSelector
**Describe the bug**
Usage of correct cssSelector for step:  When I find comparisonRule `number` elements by `locator` and for each element dostepsToExecute
Gives error:
java.lang.IllegalArgumentException: Illegal visibility type ..... Expected one of 'visible', 'invisible', 'all'
	at org.vividus.ui.action.search.Visibility.lambda$getElementType$1(Visibility.java:62)
	at java.base/java.util.Optional.orElseThrow(Optional.java:401)
	at org.vividus.ui.action.search.Visibility.getElementType(Visibility.java:60)
	at org.vividus.ui.util.LocatorConversionUtils.convertToLocator(LocatorConversionUtils.java:71)
	at org.jbehave.core.steps.ParameterConverters$FunctionalParameterConverter.convertValue(ParameterConverters.java:636)
	at org.jbehave.core.steps.ParameterConverters.applyConverters(ParameterConverters.java:337)
	at org.jbehave.core.steps.ParameterConverters.convert(ParameterConverters.java:346)
	at org.vividus.bdd.steps.ParameterConvertersDecorator.convertAdaptedValue(ParameterConvertersDecorator.java:86)
	at org.vividus.bdd.steps.ParameterConvertersDecorator.convert(ParameterConvertersDecorator.java:59)
	at org.jbehave.core.steps.StepCreator.convertParameterValues(StepCreator.java:442)
	at org.jbehave.core.steps.StepCreator.access$1400(StepCreator.java:51)
	at org.jbehave.core.steps.StepCreator$ParametrisedStep.parametriseStep(StepCreator.java:918)
	at org.jbehave.core.steps.StepCreator$ParametrisedStep.perform(StepCreator.java:858)
	at org.jbehave.core.steps.StepCreator$ReportingAbstractStep.perform(StepCreator.java:686)
	at org.jbehave.core.embedder.PerformableTree$FineSoFar.run(PerformableTree.java:387)
	at org.jbehave.core.embedder.PerformableTree$PerformableSteps.perform(PerformableTree.java:1335)
	at org.jbehave.core.embedder.PerformableTree$AbstractPerformableScenario.perform(PerformableTree.java:1214)
	at org.jbehave.core.embedder.PerformableTree$AbstractPerformableScenario.performRestartableSteps(PerformableTree.java:1193)
	at org.jbehave.core.embedder.PerformableTree$AbstractPerformableScenario.performScenario(PerformableTree.java:1205)
	at org.jbehave.core.embedder.PerformableTree$NormalPerformableScenario.perform(PerformableTree.java:1252)
	at org.jbehave.core.embedder.PerformableTree$PerformableScenario.perform(PerformableTree.java:1108)
	at org.jbehave.core.embedder.PerformableTree$PerformableStory.performScenarios(PerformableTree.java:997)
	at org.jbehave.core.embedder.PerformableTree$PerformableStory.perform(PerformableTree.java:964)
	at org.jbehave.core.embedder.PerformableTree.performCancellable(PerformableTree.java:471)
	at org.jbehave.core.embedder.PerformableTree.perform(PerformableTree.java:438)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:299)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:272)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

**To Reproduce**
When I find >= `1` elements by `By.cssSelector(a:not([href*='cookie']):not([href*='terms']))` and for each element do

**Expected behavior**
Step find elements via correct cssSelector

**Execution environment (please complete the following information):**
 - Vividus version: 0.3.7
 - OS: Windows 10
 - Java:  Java HotSpot(TM) 64-Bit Server VM, JAVA_VERSION="14", mixed mode, sharing

**Desktop Web (if applicable, please complete the following information):**
 - OS: Windows 10
 - Browser: chrome

### PR DESCRIPTION
**Pull request by abudevich**
Fixes #1993

### CODE REVIEW

File: vividus-extension-selenium/src/test/java/org/vividus/ui/util/LocatorConversionUtilsTests.java [hunk 1]
```diff
@@ -73,7 +73,10 @@
                 TestLocatorType.FILTER, VALUE)
                 .addFilter(TestLocatorType.FILTER, VALUE)
                 .addFilter(TestLocatorType.FILTER, VALUE),
-                "By.search(value):i->filter.filter(value).filter(value).filter(value)")
+                "By.search(value):i->filter.filter(value).filter(value).filter(value)"),
+            Arguments.of(createAttributes(TestLocatorType.SEARCH, "value:not([attribute*='test'])",
+                    Visibility.INVISIBLE, TestLocatorType.FILTER, VALUE),
+                    "By.search(value:not([attribute*='test'])):i->filter.filter(value)")
```
Comment (valfirst) [inline vividus-extension-selenium/src/test/java/org/vividus/ui/util/LocatorConversionUtilsTests.java:79]:
```suggestion
                Visibility.INVISIBLE, TestLocatorType.FILTER, VALUE),
                "By.search(value:not([attribute*='test'])):i->filter.filter(value)")
```

**Review by valfirst — CHANGES_REQUESTED** [review]

**Review by ikalinin1 — APPROVED** [review]

**Review by valfirst — APPROVED** [review]
