### PR TITLE
Fixed 'Step to add single HTTP header to request #881'

### LINKED ISSUE #881: Step to add single HTTP header to request
Today exists the only way to provide HTTP headers to the request:  
`When I set request headers:headers`  
This is the way to overwrite all HTTP headers.  

Need to have a step, adding headers instead of overwrite them, eg:  
```
When I add request header with name `$name` and value `$value`
```

### PR DESCRIPTION
**Pull request by TatianaTochko**
Fixes #881

### CODE REVIEW

File: vividus-plugin-rest-api/src/main/java/org/vividus/http/HttpTestContext.java [hunk 1]
```diff
@@ -48,6 +48,11 @@ public void putRequestHeaders(List<Header> requestHeaders)
         getData().requestHeaders = requestHeaders;
     }
 
+    public void addRequestHeaders(List<Header> requestHeaders)
+    {
+        getData().requestHeaders.addAll(requestHeaders);
```
Comment (valfirst) [inline vividus-plugin-rest-api/src/main/java/org/vividus/http/HttpTestContext.java:53]: please add unit tests

**Review by valfirst — CHANGES_REQUESTED** [review]

File: vividus-tests/src/main/resources/story/integration/RestApiStepsTests.story [hunk 2]
```diff
@@ -36,3 +36,17 @@ Scenario: Verify step "Then the connection is secured using $securityProtocol pr
...
 Then the connection is secured using TLSv1.2 protocol
+
+Scenario: Verify step "I add request headers:$headers"
+Given request body: ${request-body}
+When I set request headers:
+|name        |value           |
+|Content-Type|application/json|
+Then `${responseCode}` is equal to `200`
+When I add request headers:
+|name          |value         |
```
Comment (valfirst) [inline vividus-tests/src/main/resources/story/integration/RestApiStepsTests.story:47]: please format in a table-like view

File: .gitignore [hunk 3]
```diff
@@ -14,3 +14,6 @@
 #Build Dirs#
 output/
 .out/**
+*.properties
+*.jar
+*.properties
```
Comment (valfirst) [inline .gitignore:19]: invalid change

File: vividus-plugin-rest-api/src/main/java/org/vividus/bdd/steps/api/HttpRequestSteps.java [hunk 4]
```diff
@@ -255,4 +265,11 @@ public void setApiEndpoint(String apiEndpoint)
     {
         this.apiEndpoint = apiEndpoint;
     }
+
+    private List<Header> getRequestHeaders(ExamplesTable headers)
```
Comment (valfirst) [inline vividus-plugin-rest-api/src/main/java/org/vividus/bdd/steps/api/HttpRequestSteps.java:269]: it's better to keep such methods before setters

**Review by valfirst — CHANGES_REQUESTED** [review]

File: docs/modules/plugins/pages/plugin-rest-api.adoc [hunk 5]
```diff
@@ -88,6 +88,37 @@ When I wait for presence of element by `$.data.testData` with `PT5S` polling int
...
+==== *_Usage_*
+
+.Sample.story
+[source,gherkin]
+----
+Scenario: Verify possobility to add request header with name and value
+When I add request headers:
+|name  |value |
+|name  |value |
+When I send HTTP POST to the relative URL '/post'
```
[the remark this answers is not in the document]
Comment (valfirst) [reply docs/modules/plugins/pages/plugin-rest-api.adoc:118]: @TatianaTochko ☝️

File: docs/modules/plugins/pages/plugin-rest-api.adoc [hunk 6]
```diff
@@ -88,6 +88,37 @@ When I wait for presence of element by `$.data.testData` with `PT5S` polling int
...
+Then a JSON element by the JSON path '$.headers.Name' is equal to '"Value"'
```
[the remark this answers is not in the document]
Comment (valfirst) [reply docs/modules/plugins/pages/plugin-rest-api.adoc:119]: @TatianaTochko ☝️

File: docs/modules/plugins/pages/plugin-rest-api.adoc [hunk 7]
```diff
@@ -88,6 +88,37 @@ When I wait for presence of element by `$.data.testData` with `PT5S` polling int
 |When I issue a HTTP GET request for a resource with the URL '${requestUrl}'|
 ----
 
+=== Adding headers to HTTP request
+
+==== *_Info_*
+
+Adds request headers to request
```
Comment (uarlouski) [inline docs/modules/plugins/pages/plugin-rest-api.adoc:95]: please include some link to docs about req headers

File: vividus-plugin-rest-api/src/main/java/org/vividus/bdd/steps/api/HttpRequestSteps.java [hunk 8]
```diff
@@ -110,12 +110,22 @@ public void putMultipartRequest(ExamplesTable requestParts)
...
+    /**
+     * Add request headers
+     * @param headers ExamplesTable representing list of headers with columns "name" and "value" specifying HTTP header
+     * names and values respectively
+     */
+    @When("I add request headers:$headers")
+    public void addRequestHeaders(ExamplesTable headers)
+    {
+        List<Header> requestHeaders = getRequestHeaders(headers);
+        httpTestContext.addRequestHeaders(requestHeaders);
```
Comment (uarlouski) [inline vividus-plugin-rest-api/src/main/java/org/vividus/bdd/steps/api/HttpRequestSteps.java:126]: maybe create function like
```
void performWithHeaders(ExamplesTable headers, Consumer<List<Header>> headersConsumer) 
```
to inline setUpRequestHeaders and addRequestHeaders methods bodies

File: docs/modules/plugins/pages/plugin-rest-api.adoc [hunk 9]
```diff
@@ -88,6 +88,37 @@ When I wait for presence of element by `$.data.testData` with `PT5S` polling int
...
+
+==== *_Usage_*
+
+.Sample.story
+[source,gherkin]
+----
+Scenario: Verify possibility to add request header with name Name and value Value
+When I add request headers:
+|name  |value |
+|Name  |Value |
```
Comment (uarlouski) [inline docs/modules/plugins/pages/plugin-rest-api.adoc:117]: please use some real header, imho example story will look better by doing this

File: vividus-plugin-rest-api/src/main/java/org/vividus/bdd/steps/api/HttpRequestSteps.java [hunk 10]
```diff
@@ -110,12 +110,22 @@ public void putMultipartRequest(ExamplesTable requestParts)
...
         httpTestContext.putRequestHeaders(requestHeaders);
     }
 
+    /**
+     * Add request headers
+     * @param headers ExamplesTable representing list of headers with columns "name" and "value" specifying HTTP header
+     * names and values respectively
+     */
+    @When("I add request headers:$headers")
+    public void addRequestHeaders(ExamplesTable headers)
```
Comment (ikalinin1) [inline vividus-plugin-rest-api/src/main/java/org/vividus/bdd/steps/api/HttpRequestSteps.java:123]: Let's use the Header converter?

Comment (ikalinin1) [reply vividus-plugin-rest-api/src/main/java/org/vividus/bdd/steps/api/HttpRequestSteps.java:123]: cc @valfirst

**Review by ikalinin1 — CHANGES_REQUESTED** [review]

File: vividus-plugin-rest-api/src/main/java/org/vividus/bdd/steps/api/HttpRequestSteps.java [hunk 11]
```diff
@@ -233,6 +242,19 @@ public void waitForResponseCode(int responseCode, Duration duration, int retryTi
         );
     }
 
+    public void performWithHeaders(ExamplesTable headers, Consumer<List<Header>> headersConsumer)
+    {
+        List<Header> requestHeaders = getRequestHeaders(headers);
+        headersConsumer.accept(requestHeaders);
+    }
+
+    private List<Header> getRequestHeaders(ExamplesTable headers)
```
Comment (valfirst) [inline vividus-plugin-rest-api/src/main/java/org/vividus/bdd/steps/api/HttpRequestSteps.java:251]: it can be inlined

File: vividus-plugin-rest-api/src/main/java/org/vividus/bdd/steps/api/HttpRequestSteps.java [hunk 12]
```diff
@@ -233,6 +242,19 @@ public void waitForResponseCode(int responseCode, Duration duration, int retryTi
         );
     }
 
+    public void performWithHeaders(ExamplesTable headers, Consumer<List<Header>> headersConsumer)
```
Comment (valfirst) [inline vividus-plugin-rest-api/src/main/java/org/vividus/bdd/steps/api/HttpRequestSteps.java:245]: it shouldn't be public

**Review by valfirst — CHANGES_REQUESTED** [review]

File: docs/modules/plugins/pages/plugin-rest-api.adoc [hunk 13]
```diff
@@ -88,6 +88,37 @@ When I wait for presence of element by `$.data.testData` with `PT5S` polling int
...
+
+[source,gherkin]
+----
+When I add request header with name `$name` and value `$value`
+----
+
+==== *_Parameters_*
+
+.  `name` - header name
+.  `value` - header value
```
Comment (valfirst) [inline docs/modules/plugins/pages/plugin-rest-api.adoc:107]:
```
.  `
```
duplicate whitespace

File: docs/modules/plugins/pages/plugin-rest-api.adoc [hunk 14]
```diff
@@ -88,6 +88,37 @@ When I wait for presence of element by `$.data.testData` with `PT5S` polling int
...
+==== *_Wording_*
+
+[source,gherkin]
+----
+When I add request header with name `$name` and value `$value`
+----
+
+==== *_Parameters_*
+
+.  `name` - header name
```
Comment (valfirst) [inline docs/modules/plugins/pages/plugin-rest-api.adoc:106]:
```
.  `
```
duplicate whitespace

File: vividus-http-client/src/main/java/org/vividus/http/exception/HttpRequestBuildException.java [hunk 15]
```diff
@@ -16,7 +16,9 @@
 
 package org.vividus.http.exception;
 
-public class HttpRequestBuildException extends Exception
+import java.io.IOException;
+
+public class HttpRequestBuildException extends IOException
```
Comment (valfirst) [inline vividus-http-client/src/main/java/org/vividus/http/exception/HttpRequestBuildException.java:21]: it's not related to the current PR

Comment (valfirst) [reply vividus-http-client/src/main/java/org/vividus/http/exception/HttpRequestBuildException.java:21]: a lot of noisy changes coming from another PRs/commits

**Review by valfirst — CHANGES_REQUESTED** [review]

File: docs/modules/plugins/pages/plugin-rest-api.adoc (hunk 7 above)
Comment (valfirst) [reply docs/modules/plugins/pages/plugin-rest-api.adoc:95]: too many `request` words in one sentence, please, make it concise

**Review by valfirst — APPROVED** [review]

**Review by uarlouski — APPROVED** [review]
