### PR TITLE
[vividus] Add duplicate step bean name validation

### LINKED ISSUE #3081: Conflicting step bean's id leads to unexpected duplicated candidate exception
STR:
Define step bean with conflicting name
```xml
   <bean id="variablesSteps" class="org.my.steps.Steps" />
   <util:list id="stepBeanNames-customSteps" value-type="java.lang.String">
        <idref bean="variablesSteps" />
   </util:list>
```

Running any test will lead to an exception similar to:
```bash
2022-08-18 11:10:30,931 [main] ERROR org.vividus.runner.StoriesRunner - org.jbehave.core.embedder.DuplicateCandidateFound: When I $actionType baseline with name `$name` using screenshot configuration:$screenshotConfiguration
	at org.jbehave.core.embedder.AllStepCandidates.lambda$new$2(AllStepCandidates.java:76)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1850)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.jbehave.core.embedder.AllStepCandidates.<init>(AllStepCandidates.java:78)
	at org.jbehave.core.embedder.StoryManager.runStories(StoryManager.java:105)
	at org.jbehave.core.embedder.StoryManager.runStoriesAsPaths(StoryManager.java:98)
	at org.vividus.BatchedEmbedder.lambda$runStoriesAsPaths$0(BatchedEmbedder.java:108)
	at org.vividus.BatchedEmbedder.generateViewAfterExecution(BatchedEmbedder.java:131)
	at org.vividus.BatchedEmbedder.runStoriesAsPaths(BatchedEmbedder.java:68)
	at org.vividus.runner.StoriesRunner.run(StoriesRunner.java:55)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.vividus.runner.AbstractTestRunner.main(AbstractTestRunner.java:69)


```

The root cause is that VIVIDUS collects the same bean step id twice.

Possible fixes:

Throw an exception in the case of conflicting step bean names

### PR DESCRIPTION
**Pull request by EDbarvinsky**
Fix #3081

### CODE REVIEW

**Comment by EDbarvinsky** [comment]
Stack trace example
image

File: vividus/src/main/java/org/vividus/steps/SpringStepFactoryBeanPostProcessor.java [hunk 1]
```diff
@@ -35,7 +38,13 @@ public Object postProcessAfterInitialization(Object bean, String beanName)
...
         {
             List<String> stepBeanNames = BeanFactoryUtils.mergeLists(applicationContext, "stepBeanNames-");
-
+            List<String> duplicateStepBeanNames = CollectionUtils.getCardinalityMap(stepBeanNames).entrySet()
+                    .stream()
+                    .filter(stepBeanNameCount -> stepBeanNameCount.getValue() > 1)
+                    .map(Map.Entry::getKey)
+                    .collect(toList());
+            Validate.validState(
+                    duplicateStepBeanNames.isEmpty(), "Duplicate step beans name found %s", duplicateStepBeanNames);
```
Comment (valfirst) [inline vividus/src/main/java/org/vividus/steps/SpringStepFactoryBeanPostProcessor.java:47]:
```suggestion
            String duplicateStepBeanNames = CollectionUtils.getCardinalityMap(stepBeanNames).entrySet()
                    .stream()
                    .filter(stepBeanNameCount -> stepBeanNameCount.getValue() > 1)
                    .map(Map.Entry::getKey)
                    .collect(Collectors.joining(", "));
            Validate.validState(
                    duplicateStepBeanNames.isEmpty(), "Duplicate step beans names are found: %s. Please, consider renaming to avoid conflicts", duplicateStepBeanNames);
```

**Review by valfirst — COMMENTED** [review]
I think you are ready to add unit tests now

File: vividus/src/main/java/org/vividus/steps/SpringStepFactoryBeanPostProcessor.java [hunk 2]
```diff
@@ -35,7 +39,15 @@ public Object postProcessAfterInitialization(Object bean, String beanName)
...
         {
             List<String> stepBeanNames = BeanFactoryUtils.mergeLists(applicationContext, "stepBeanNames-");
-
+            String duplicateStepBeanNames = stepBeanNames.stream()
+                    .collect(Collectors.groupingBy(Function.identity(), Collectors.counting()))
+                    .entrySet().stream()
+                    .filter(stepBeanNameCount -> stepBeanNameCount.getValue() > 1)
+                    .map(Map.Entry::getKey)
+                    .collect(Collectors.joining(", "));
+            Validate.validState(duplicateStepBeanNames.isEmpty(),
```
Comment (EDbarvinsky) [inline vividus/src/main/java/org/vividus/steps/SpringStepFactoryBeanPostProcessor.java:48]: on the same way as was suggested by @ikalinin1  to avoid dependecy on 3rd party lib on `CollectionUtils` make sense to   replace `Validate#validState` with `if(condition ) { throw new Exc(Stringformat(bla-bla))}` ?

Comment (valfirst) [reply vividus/src/main/java/org/vividus/steps/SpringStepFactoryBeanPostProcessor.java:48]: please keep `Validate#validState`

**Review by valfirst — APPROVED** [review]

**Review by ikalinin1 — APPROVED** [review]

**Review by uarlouski — APPROVED** [review]
