### PR TITLE
[allure-adaptor] Include know-issues in pass rate

### LINKED ISSUE #4662: [Report/'Overview' tab/'Doughnut' chart] Incorrect % of pass rate
Pass Rate % on the 'Doughnut' chart is calculated incorrectly inside the chart. 
**NOTE:** Bug is reproduced only for 'Overall Pass Rate' inside the circle of the 'Doughnut' chart (%numbers on the 'Doughnut' cirle are calculated correctly).
_**Example:**_ 
Amount of test cases: 111
**Known Issue: 21/111=18.91%**
Known
**Failed: 2/111=1.8%**
Failed
**Broken: 1/111=0.9%**
Broken
**Passed: 87/111=78.37%**
Passed

**Overall: 96.66%** - the number does not match any calculations 

**Steps to reproduce:**
1. Run the tests to receive the Allure report;
2. Open report;
3. Click 'Overall' tab;
4. Observe the 'Doughnut' chart with pass rate

**Expected result:** % is calculated correctly inside the 'Doughnut' chart (**TBD:** 100%-Known%-Failed%-Broken%=Passed%)
**Actual result:** % is calculated incorrectly inside the 'Doughnut' chart

**Execution environment:**
 - Vividus version: 0.6.5-SNAPSHOT

### PR DESCRIPTION
**Pull request by draker94**
Closes #4662

### CODE REVIEW

File: vividus-allure-adaptor/src/test/java/org/vividus/report/allure/adapter/AllureReportPatchingConsistencyTests.java [hunk 1]
```diff
@@ -51,6 +55,7 @@ static Stream<Arguments> allureSourceContainsText()
     @MethodSource("allureSourceContainsText")
     void testAllureSourceContainsText(String fileName, String text) throws IOException
     {
+        System.out.println(readFile(fileName));
```
Comment (valfirst) [inline vividus-allure-adaptor/src/test/java/org/vividus/report/allure/adapter/AllureReportPatchingConsistencyTests.java:58]:
```suggestion
```

**Review by valfirst — APPROVED** [review]
