### PR TITLE
[vividus-to-zephyr-exporter] Fix validation for zephyr.exporter.source-directory

### LINKED ISSUE #3040: NPE error is displayed in the logs to zephyr-to-vividus plugin
NullPointerException is shown in the error logs when zephyr.exporter.source-directory is not valid.

**Steps to reproduce:**
1. In vividus-to-zephyr exporter properties file leave zephyr.exporter.source-directory parameter empty or enter non-existent path (e.g. zephyr.exporter.source-directory=output/qwerty/)
2. Run any story and wait until vividus-to-zephyr export stage is failed
3. Look at logs.

**Expected result:** no NPE error displayed, instead there should be clear error message describing what exactly happened.

**Artifacts**
logs: 
[log.txt](https://github.com/vividus-framework/vividus/files/9289776/log.txt)

**Execution environment (please complete the following information):**
 - Vividus version: 0.4.9
 - Java: Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.12+8-LTS-237, mixed mode)

### PR DESCRIPTION
**Pull request by VolhaHurynovich**
Fixes #3040

### CODE REVIEW

**Review by ikalinin1 — APPROVED** [review]

File: vividus-to-zephyr-exporter/src/main/java/org/vividus/zephyr/configuration/ZephyrExporterProperties.java [hunk 1]
```diff
@@ -19,17 +19,19 @@
...
 import org.vividus.zephyr.model.TestCaseStatus;
 
+@Validated
 @ConfigurationProperties("zephyr.exporter")
 public class ZephyrExporterProperties
 {
     private String jiraInstanceKey;
 
-    @NotBlank(message = "Property 'zephyr.exporter.source-directory' must not be blank")
+    @NotNull(message = "Property 'zephyr.exporter.source-directory' must be set")
```
Comment (valfirst) [inline vividus-to-zephyr-exporter/src/main/java/org/vividus/zephyr/configuration/ZephyrExporterProperties.java:34]: how does this change fix the issue?

Comment (VolhaHurynovich) [reply vividus-to-zephyr-exporter/src/main/java/org/vividus/zephyr/configuration/ZephyrExporterProperties.java:34]: It helps when property is empty, but in case of a non-existent path, we are facing with NoSuchFileException (just like now)
Property is empty:
image

Non-existent path:
image

Comment (VolhaHurynovich) [reply vividus-to-zephyr-exporter/src/main/java/org/vividus/zephyr/configuration/ZephyrExporterProperties.java:34]: If we want to see clear message, I can add try-catch:

        try
        {
            Files.walkFileTree(zephyrExporterProperties.getSourceDirectory(), crawler);
        }
        catch (IOException e)
        {
            throw new NoSuchFileException("Path to directory with test execution JSON results should be corrected: "
                    + zephyrExporterProperties.getSourceDirectory());
        }
or create new annotation @FileByPathExists

**Review by valfirst — APPROVED** [review]
