### PR TITLE
[plugin-web-app] Do not set acceptInsecureCerts for Safari and IE

### LINKED ISSUE #1192: The Sauce VMs failed to start the browser or device. Infrastructure Error (Safari)
**Describe the bug**
Usual run of a test on Vividus 0.2.10 in Safari browser with SauceLabs enabled leads to an error:
Infrastructure Error -- The Sauce VMs failed to start the browser or device.
For more info, please check https://wiki.saucelabs.com/display/DOCS/Common+Error+Messages (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 27.21 seconds
Build info: version: '4.0.0-alpha-1', revision: 'd1d3728cae', time: '2019-04-24T13:42:21'
System info: host: 'EPBYMINW00E3', ip: '192.168.88.252', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '14.0.2'
Driver info: driver.version: RemoteWebDriver

**To Reproduce**
Given I am on a page with the URL 'https://shop.googlemerchandisestore.com'

**Expected behavior**
The page is loaded

**Artifacts**
[log4.log](https://github.com/vividus-framework/vividus/files/5634757/log4.log)

**Execution environment (please complete the following information):**
 - Vividus version: [0.2.10]
 - OS: [macos 10.14]
 - Java: [jdk-14.0.2]
 - Saucelab log: 
[log.txt](https://github.com/vividus-framework/vividus/files/5634846/log.txt)

**Desktop Web (if applicable, please complete the following information):**
 - OS: [macos 10.14]
 - Browser [safari]
 - Version [12]

### PR DESCRIPTION
**Pull request by ikalinin1**
Fixes #1192

### CODE REVIEW

File: vividus-plugin-web-app/src/main/java/org/vividus/selenium/WebDriverType.java [hunk 1]
```diff
@@ -81,6 +81,7 @@ public void prepareCapabilities(DesiredCapabilities desiredCapabilities)
             // Workaround for IExplore:
             // https://stackoverflow.com/questions/50287435/actions-movetoelement-not-working-on-ie-11
             desiredCapabilities.merge(new InternetExplorerOptions().requireWindowFocus());
+            disableAcceptInsecureCertificates(desiredCapabilities);
```
Comment (uarlouski) [inline vividus-plugin-web-app/src/main/java/org/vividus/selenium/WebDriverType.java:84]: can you please describe in few words why its needed

**Review by uarlouski — APPROVED** [review]

File: vividus-plugin-web-app/src/main/java/org/vividus/selenium/WebDriverType.java (hunk 1 above)
Comment (valfirst) [reply vividus-plugin-web-app/src/main/java/org/vividus/selenium/WebDriverType.java:84]: what about just changing this code:
https://github.com/vividus-framework/vividus/blob/master/vividus-extension-selenium/src/main/java/org/vividus/selenium/AbstractVividusWebDriverFactory.java#L68 ?
can we check if IE || Safari and then skip adding of this capability?

the problem with current approach is that users may set the capability and expect the changes in browser behavior, but we just silently remove this capability

**Review by valfirst — CHANGES_REQUESTED** [review]

**Review by valfirst — APPROVED** [review]

**Review by uarlouski — APPROVED** [review]
