### PR TITLE
Trends

### LINKED ISSUE #406: Enable trends in Vividus implementation of Allure
In order to provide more visibility over test runs over time we need to enable a few trending options in Vividus allure report:

1. Have a trend that shows the overall passed/failed status by builds.
Smtn similar to this:
https://user-images.githubusercontent.com/29943195/35208079-0518a7ba-ff79-11e7-81de-67d740d1a6be.png

2. Have a trend which shows test status by tests by builds
Test | Build #1 | Build #2 | ... | Build #n
Test 1 | Passed | Passed | ... | Passed
Test 2 | Passed | Failed | ... | Failed
Test n | Passed | Passed | ... | Failed

Smtn like this: https://plugins.jenkins.io/test-results-analyzer/

3. Have a graph of test coverage: Tests by features
Where we can tag each scenario with some value like 'registration'
And this graph will return the #of scenarios per tag/feature
Allure Report 2020-03-19 19-52-14

4. If there are any other trends , for ex: execution time trend or # of tests or any other fancy trends that can be easily implemented, that would be a benefit

### PR DESCRIPTION
**Pull request by uarlouski**
Closes #406

### CODE REVIEW

File: vividus-allure-adaptor/src/main/java/org/vividus/bdd/report/allure/AllureReportGenerator.java [hunk 1]
```diff
@@ -130,12 +143,14 @@ private void patchAllureFiles() throws IOException
...
+        String brokenStatusColor = "#d35ebf";
         javascriptString = javascriptString
+                .replace("#aaa", brokenStatusColor)
                 .replace("unknown:\"Unknown\"", "unknown:\"Known\"")
                 .replace("\"failed\",\"broken\",\"passed\",\"skipped\",\"unknown\"",
-                        "\"passed\",\"unknown\",\"failed\",\"broken\",\"skipped\"");
+                        "\"failed\",\"unknown\",\"passed\",\"broken\",\"skipped\"");
         cssString = cssString
-                .replace("#ffd050", "#d35ebf")
+                .replaceAll("#ffd050", brokenStatusColor)
```
Comment (valfirst) [inline vividus-allure-adaptor/src/main/java/org/vividus/bdd/report/allure/AllureReportGenerator.java:153]: why is `replace` changed to `replaceAll` ?

File: vividus-allure-adaptor/src/main/java/org/vividus/bdd/report/allure/AllureReportGenerator.java [hunk 2]
```diff
@@ -130,12 +143,14 @@ private void patchAllureFiles() throws IOException
         String javascriptString = FileUtils.readFileToString(javascriptFile, StandardCharsets.UTF_8);
         String cssString = FileUtils.readFileToString(cssFile, StandardCharsets.UTF_8);
 
+        String brokenStatusColor = "#d35ebf";
         javascriptString = javascriptString
+                .replace("#aaa", brokenStatusColor)
```
Comment (valfirst) [inline vividus-allure-adaptor/src/main/java/org/vividus/bdd/report/allure/AllureReportGenerator.java:148]: could you please put comment what `#aaa` is?

File: vividus-allure-adaptor/src/main/java/org/vividus/bdd/report/allure/AllureReportGenerator.java (hunk 1 above)
Comment (uarlouski) [reply vividus-allure-adaptor/src/main/java/org/vividus/bdd/report/allure/AllureReportGenerator.java]: useless change :)
