### PR TITLE
551

### LINKED ISSUE #551: Scrolling is stuck when trying to check navigation components
**Describe the bug**
When trying to check navigation elements on the page (button that redirects from bottom to top, redirection within the page), step Then the page is scrolled to an element with the attribute ' '=' ' is failed as scrolling stucks.

**To Reproduce**
Attaching 2 scenarios:
[Case1.txt](https://github.com/vividus-framework/vividus/files/4602868/Case1.txt)
[Case2.txt](https://github.com/vividus-framework/vividus/files/4602885/Case2.txt)

**Expected behavior**
Page should be scrolled to particular element

**Artifacts**
Attaching Allure reports:
Case1:
[allure.zip](https://github.com/vividus-framework/vividus/files/4602897/allure.zip)
Case2:
[allure.zip](https://github.com/vividus-framework/vividus/files/4602884/allure.zip)

**Execution environment (please complete the following information):**
 - Vividus version: 0.2.2
 - OS: Win10
 - Java: JDK13

**Desktop Web (if applicable, please complete the following information):**
 - OS: Win10
 - Browser Chrome

### PR DESCRIPTION
**Pull request by ikalinin1**
closes #551

### CODE REVIEW

File: vividus-plugin-web-app/src/main/java/org/vividus/bdd/steps/ui/web/WaitSteps.java [hunk 1]
```diff
@@ -457,6 +459,16 @@ public boolean waitForElementDisappearance(SearchAttributes locator)
                 .isWaitPassed();
     }
 
+    /**
+     * Waits for the scroll finish; Could be useful for the cases when you have very slow scroll
+     * and need to synchronize the tests with the scroll
+     */
+    @When("I wait until scroll finished")
```
Comment (valfirst) [inline vividus-plugin-web-app/src/main/java/org/vividus/bdd/steps/ui/web/WaitSteps.java:466]: `I wait until scroll is finished`
