### PR TITLE
[bdd-engine] Fix invalid exceptions thrown from sub steps

### LINKED ISSUE #1564: Error message in Allure report about step deletion is not obvious
Step When I switch to a frame by the xpath '$xpath' was depricated and removed starting from Vividus version 0.3.0 and replaced with When I switch to frame located `$locator`.

Using the old step on version 0.3.0 brakes scenarios, but the error message about the failure root cause is not obvious.

Message update is needed.
[logs.txt](https://github.com/vividus-framework/vividus/files/6310392/logs.txt)

### PR DESCRIPTION
**Pull request by uarlouski**
Closes #1564

### CODE REVIEW

File: vividus-bdd-engine/src/main/java/org/vividus/bdd/steps/SubSteps.java [hunk 1]
```diff
@@ -88,6 +88,10 @@ else if (rootCause instanceof Error)
         {
             throw (Error) rootCause;
         }
+        else if (rootCause instanceof UUIDExceptionWrapper)
+        {
+            throw new UUIDExceptionWrapper(rootCause);
```
Comment (valfirst) [inline vividus-bdd-engine/src/main/java/org/vividus/bdd/steps/SubSteps.java:93]: double-wrapping?

Comment (uarlouski) [reply vividus-bdd-engine/src/main/java/org/vividus/bdd/steps/SubSteps.java:93]: - https://github.com/jbehave/jbehave-core/blob/master/jbehave-core/src/main/java/org/jbehave/core/steps/StepCreator.java#L889
- and as per unit tests
- technically this is a single wrapping
Screenshot 2021-05-19 at 11 59 14

**Review by valfirst — APPROVED** [review]

File: vividus-bdd-engine/src/main/java/org/vividus/bdd/steps/SubSteps.java (hunk 1 above)
Comment (valfirst) [reply vividus-bdd-engine/src/main/java/org/vividus/bdd/steps/SubSteps.java:94]: `throw stepResult.getFailure();` ?

**Review by valfirst — CHANGES_REQUESTED** [review]

**Review by valfirst — APPROVED** [review]

**Review by ikalinin1 — APPROVED** [review]
