### PR TITLE
[allure-adaptor] Fix reporting of scenarios with same name

### LINKED ISSUE #1513: Allure report does not show all scenarios in a story when scenario names are not unique in a story and there is story-level examples table
**Describe the bug**
If there are completely the same scenario names in a story AND there is story-level examples table, only the last such scenario is shown in allure report. 
The 1st scenario with not unique name is skipped in allure report.
As I see Vividus runs all scenarios in reality.

It does not matter what steps are used in such scenarios. The root cause is not unique scenario name.

Please see the attached screenshots, reports and logs.

**Execution environment (please complete the following information):**
vividusVersion = '0.3.2'

### PR DESCRIPTION
**Pull request by ikalinin1**
Fixes #1513

### CODE REVIEW

File: vividus-allure-adaptor/src/main/java/org/vividus/bdd/report/allure/AllureStoryReporter.java [hunk 1]
```diff
@@ -606,13 +607,16 @@ private String getHistoryId(RunningStory runningStory, RunningScenario runningSc
...
                 .collect(Collectors.joining(" > "));
 
-        List<Scenario> scenariosWithTitle = runningStory.getStory().getScenarios().stream()
-                .filter(scenario -> scenario.getTitle().equals(runningScenario.getScenario().getTitle()))
-                .collect(Collectors.toList());
+        String currentScenarioTitle = runningScenario.getScenario().getTitle();
+        long scenarioWithSameTitle = runningStory.getRanScenarios()
+                                                 .stream()
+                                                 .map(Scenario::getTitle)
+                                                 .filter(title ->  currentScenarioTitle.equals(title))
```
Comment (valfirst) [inline vividus-allure-adaptor/src/main/java/org/vividus/bdd/report/allure/AllureStoryReporter.java:614]: currentScenarioTitle::equals

**Review by valfirst — CHANGES_REQUESTED** [review]

File: vividus-allure-adaptor/src/main/java/org/vividus/bdd/report/allure/AllureStoryReporter.java (hunk 1 above)
Comment (ikalinin1) [reply vividus-allure-adaptor/src/main/java/org/vividus/bdd/report/allure/AllureStoryReporter.java:614]: Good  🎣

**Review by valfirst — APPROVED** [review]

**Review by abudevich — APPROVED** [review]

File: vividus-bdd-engine/src/test/java/org/vividus/bdd/model/RunningStoryTests.java [hunk 2]
```diff
@@ -0,0 +1,43 @@
...
+
+import java.util.List;
+
+import org.jbehave.core.model.Scenario;
+import org.junit.jupiter.api.Test;
+
+class RunningStoryTests
+{
+    @Test
+    void shouldReturnRanScenarios()
```
Comment (abudevich) [inline vividus-bdd-engine/src/test/java/org/vividus/bdd/model/RunningStoryTests.java:31]: `shouldReturnRanScenarios`-> `shouldReturnRunScenarios`?
