### PR TITLE
Attachments

### LINKED ISSUE #975: Integrate Vividus with Report Portal v.5.0 so that logs and screenshots are available
**Steps to reproduce:**
- add next dependency into build.gradle:
compile group: 'org.vividus', name: 'vividus-agent-reportportal', version: '0.2.5'

- create reportportal.properties file with values:
system.rp.enable=true
system.rp.endpoint=https://reportportal.epam.com
system.rp.uuid=***
system.rp.launch=LOCAL_LAUNCH
system.rp.project=***

-run stories -> launch is created in RP, stack trace and attachments are not available for failed steps

image

### PR DESCRIPTION
**Pull request by ikalinin1**
image

Fixes #975

### CODE REVIEW

File: vividus-agent-reportportal/src/main/java/org/vividus/reportportal/listener/AttachmentListener.java [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+
+import rp.com.google.common.io.BaseEncoding;
+
+public class AttachmentListener
+{
+    private static final Logger LOGGER = LoggerFactory.getLogger(AttachmentListener.class);
+
+    public AttachmentListener(EventBus eventBus)
+    {
+        eventBus.register(this);
```
Comment (valfirst) [inline vividus-agent-reportportal/src/main/java/org/vividus/reportportal/listener/AttachmentListener.java:38]: I think it's not needed, see `SubscriberRegisteringBeanPostProcessor `

File: vividus-agent-reportportal/src/main/java/org/vividus/reportportal/listener/AttachmentListener.java [hunk 2]
```diff
@@ -0,0 +1,49 @@
...
+    }
+
+    @Subscribe
+    @AllowConcurrentEvents
+    public void onAttachmentPublish(AttachmentPublishEvent event) throws IOException
+    {
+        Attachment attachment = event.getAttachment();
+        LOGGER.info("RP_MESSAGE#BASE64#{}#{}", BaseEncoding.base64().encode(attachment.getContent()),
```
Comment (valfirst) [inline vividus-agent-reportportal/src/main/java/org/vividus/reportportal/listener/AttachmentListener.java:46]: what about HTML attachments? and all other attachment which are not images?

**Review by valfirst — CHANGES_REQUESTED** [review]

File: vividus-agent-reportportal/src/main/java/org/vividus/reportportal/listener/AttachmentListener.java (hunk 2 above)
Comment (ikalinin1) [reply vividus-agent-reportportal/src/main/java/org/vividus/reportportal/listener/AttachmentListener.java:46]: On the screenshot an example of HTML

**Review by uarlouski — APPROVED** [review]

**Review by valfirst — APPROVED** [review]
