### PR TITLE
[plugin-web-app-to-rest-api] Fix invalid relative url resolution in resource steps

### LINKED ISSUE #1837: "Then all resources by selector `$cssSelector` are valid on:$pages " is broken when web-application.main-page-url=   empty
**Describe the bug**
"Then all resources by selector `$cssSelector` are valid on:$pages " is broken when web-application.main-page-url=   empty

**To Reproduce**
Lifecycle:
Examples:
|pageToValidate          |
|${baseAppURL}|

Scenario: Header verify logo leads to main page
Meta:
    @layout desktop chrome_tablet chrome_phone
Given I login to web application as Beauty Advisor

Scenario: Verify Tabs
When I hover a mouse over an element with the xpath '//header//*[@data-testid='navigation.items.brands']'

Scenario: Verification of Then all resources by selector $cssSelector from $html are valid; Source from HTTP response
When I issue a HTTP GET request for a resource with the URL '<pageToValidate>'
Then all resources by selector `a` from ${response} are valid

Scenario: Verification of Then all resources by selector $cssSelector are valid on:$pages
Then all resources by selector `a` are valid on:
|pages                                       |
|<pageToValidate>                            |

**Expected behavior**
Step should work independently of set properties

**Execution environment (please complete the following information):**
 - Vividus version:  0.3.8-SNAPSHOT
 - OS: macOS Big Sur 11.4
 - Java: JDK 16

**Desktop Web (if applicable, please complete the following information):**

 - Browser Chrome

[log4 (1).log](https://github.com/vividus-framework/vividus/files/6907854/log4.1.log)

### PR DESCRIPTION
**Pull request by uarlouski**
Fixed #1837

### CODE REVIEW

File: vividus-plugin-html/src/main/java/org/vividus/util/HtmlUtils.java [hunk 1]
```diff
@@ -28,7 +28,12 @@ private HtmlUtils()
 
     public static Elements getElements(String html, String cssSelector)
     {
-        Document document = Jsoup.parse(html);
+        return getElements("", html, cssSelector);
```
Comment (valfirst) [inline vividus-plugin-html/src/main/java/org/vividus/util/HtmlUtils.java:31]: how is empty base URI treated by Jsoup?

File: docs/modules/plugins/pages/plugin-web-app-to-rest-api.adoc [hunk 2]
```diff
@@ -10,6 +10,39 @@ The plugin provides the integration between web application testing functionalit
...
+== Steps
+
+=== Check resources
+
+Check availability of resources on web pages
+
+Availability check logic:
+
+. If the `pages` row contains relative URL then it gets resolved against URL in `web-application.main-page-url` property
+. Gather elements by the CSS selector from each page
```
Comment (valfirst) [inline docs/modules/plugins/pages/plugin-web-app-to-rest-api.adoc:22]:
```suggestion
. Collect elements by the CSS selector from each page
```

File: docs/modules/plugins/pages/plugin-web-app-to-rest-api.adoc [hunk 3]
```diff
@@ -10,6 +10,39 @@ The plugin provides the integration between web application testing functionalit
...
+. Get either `href` or `src` value from each element
+. For each received value execute https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/HEAD[HEAD] request
+.. If the status code is https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/200[200 OK] then the check considered as passed
```
Comment (valfirst) [inline docs/modules/plugins/pages/plugin-web-app-to-rest-api.adoc:25]:
```suggestion
.. If the status code is https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/200[200 OK] then the check is considered as passed
```

File: docs/modules/plugins/pages/plugin-web-app-to-rest-api.adoc [hunk 4]
```diff
@@ -10,6 +10,39 @@ The plugin provides the integration between web application testing functionalit
...
+.. If the status code if one of https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404[404 Not Found], https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405[405 Method Not Allowed], https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/501[501 Not Implemented], https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503[503 Service Unavailable] then GET request will be sent
```
Comment (valfirst) [inline docs/modules/plugins/pages/plugin-web-app-to-rest-api.adoc:26]:
```suggestion
.. If the status code if one of https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404[404 Not Found], https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405[405 Method Not Allowed], https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/501[501 Not Implemented], https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503[503 Service Unavailable] then GET request will be executed
```

File: docs/modules/plugins/pages/plugin-web-app-to-rest-api.adoc [hunk 5]
```diff
@@ -10,6 +10,39 @@ The plugin provides the integration between web application testing functionalit
...
+.. If the https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/GET[GET] status code is https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/200[200 OK] then check considered as passed, otherwise failed
```
Comment (valfirst) [inline docs/modules/plugins/pages/plugin-web-app-to-rest-api.adoc:27]:
```suggestion
.. If the https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/GET[GET] status code is https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/200[200 OK] then check is considered as passed, otherwise failed
```

File: vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/bdd/steps/integration/ResourceCheckSteps.java [hunk 6]
```diff
@@ -43,14 +46,14 @@
...
 import org.vividus.testcontext.ContextCopyingExecutor;
 import org.vividus.ui.web.configuration.WebApplicationConfiguration;
-import org.vividus.util.HtmlUtils;
 import org.vividus.util.UriUtils;
 import org.vividus.validator.model.WebPageResourceValidation;
 
 public class ResourceCheckSteps
 {
     private static final Set<String> ALLOWED_SCHEMES = Set.of("http", "https");
     private static final String EXCLUDE_PATTERN = "#";
```
Comment (valfirst) [inline vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/bdd/steps/integration/ResourceCheckSteps.java:55]:
```suggestion
    private static final String URL_FRAGMENT = "#";
```

File: vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/bdd/steps/integration/ResourceCheckSteps.java [hunk 7]
```diff
@@ -160,9 +158,22 @@ private String getSelector(Element element)
...
-    private Optional<String> getElementAttribute(Element element, String attributeKey)
+    private static Optional<String> getHrefAttribute(Element element)
     {
-        return element.hasAttr(attributeKey) ? Optional.of(element.attr(attributeKey)) : Optional.empty();
+        String href = element.attr(HREF_ATTR);
+        if (!href.isEmpty())
+        {
+            if (EXCLUDE_PATTERN.equals(href))
+            {
+                return Optional.of(href);
```
Comment (valfirst) [inline vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/bdd/steps/integration/ResourceCheckSteps.java:168]: what is the point to validate URL with an empty URL fragment?

**Review by valfirst — CHANGES_REQUESTED** [review]

File: vividus-plugin-html/src/main/java/org/vividus/util/HtmlUtils.java (hunk 1 above)
Comment (uarlouski) [reply vividus-plugin-html/src/main/java/org/vividus/util/HtmlUtils.java:31]: the base URI is used to resolve relative urls, if it's empty then relative urls are returned as is (default behaviour)

File: vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/bdd/steps/integration/ResourceCheckSteps.java (hunk 7 above)
Comment (uarlouski) [reply vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/bdd/steps/integration/ResourceCheckSteps.java:168]: it's filtered prior to resource validation

File: vividus-plugin-web-app-to-rest-api/src/test/java/org/vividus/bdd/steps/integration/ResourceCheckStepsTests.java [hunk 8]
```diff
@@ -193,7 +196,11 @@ void shouldCheckResourcesFromPages() throws IOException, InterruptedException, E
         resourceCheckSteps.init();
         ExamplesTable examplesTable =
                 new ExamplesTable("|pages|\n|https://first.page|\n|https://second.page|");
-        when(webApplicationConfiguration.getMainApplicationPageUrl()).thenReturn(VIVIDUS_URI);
+        lenient().doAnswer(call ->
+        {
+            Sleeper.sleep(5, TimeUnit.SECONDS);
```
Comment (ikalinin1) [inline vividus-plugin-web-app-to-rest-api/src/test/java/org/vividus/bdd/steps/integration/ResourceCheckStepsTests.java:201]: isn't too much?

File: docs/modules/plugins/pages/plugin-web-app-to-rest-api.adoc (hunk 4 above)
Comment (ikalinin1) [inline docs/modules/plugins/pages/plugin-web-app-to-rest-api.adoc:26]: if one of -> is one of

File: docs/modules/plugins/pages/plugin-web-app-to-rest-api.adoc [hunk 9]
```diff
@@ -10,6 +10,39 @@ The plugin provides the integration between web application testing functionalit
...
 
+== Steps
+
+=== Check resources
+
+Check availability of resources on web pages
+
+Availability check logic:
+
+. If the `pages` row contains relative URL then it gets resolved against URL in `web-application.main-page-url` property
```
Comment (ikalinin1) [inline docs/modules/plugins/pages/plugin-web-app-to-rest-api.adoc:21]: `resolved ` does it make sense to describe what is resolution process?

File: docs/modules/plugins/pages/plugin-web-app-to-rest-api.adoc (hunk 5 above)
Comment (ikalinin1) [reply docs/modules/plugins/pages/plugin-web-app-to-rest-api.adoc:27]: check -> resource validation ?

File: vividus-plugin-web-app-to-rest-api/src/test/java/org/vividus/bdd/steps/integration/ResourceCheckStepsTests.java (hunk 8 above)
Comment (uarlouski) [reply vividus-plugin-web-app-to-rest-api/src/test/java/org/vividus/bdd/steps/integration/ResourceCheckStepsTests.java:201]: the exact min value is hard to determine, I would need to run the test ~100 times to ensure that the test is not flaky with given sleep time, to avoid spending my time for this I decided to take 5 sec since it's 100% enough

Comment (ikalinin1) [reply vividus-plugin-web-app-to-rest-api/src/test/java/org/vividus/bdd/steps/integration/ResourceCheckStepsTests.java:201]: Have you noticed it failing with 1 sec?

File: docs/modules/plugins/pages/plugin-web-app-to-rest-api.adoc [hunk 10]
```diff
@@ -10,6 +10,39 @@ The plugin provides the integration between web application testing functionalit
...
+
+=== Validate resources
+
+Validates resources on web pages
+
+Resource validation logic:
+
+. If the `pages` row contains relative URL then it gets resolved against URL in `web-application.main-page-url` property, i.e. if the main page URL is `https://elderscrolls.bethesda.net/` and relative url is `/skyrim10` the resulting URL will be `https://elderscrolls.bethesda.net/skyrim10`
+. Collect elements by the CSS selector from each page
+. Get either `href` or `src` value from each element
```
Comment (ikalinin1) [inline docs/modules/plugins/pages/plugin-web-app-to-rest-api.adoc:23]: what if both of them are missing?

File: vividus-plugin-html/src/main/java/org/vividus/util/HtmlUtils.java (hunk 1 above)
Comment (ikalinin1) [reply vividus-plugin-html/src/main/java/org/vividus/util/HtmlUtils.java:31]: org.jsoup.Jsoup.parse(String html) ?

File: vividus-plugin-web-app-to-rest-api/src/test/java/org/vividus/bdd/steps/integration/ResourceCheckStepsTests.java (hunk 8 above)
Comment (uarlouski) [reply vividus-plugin-web-app-to-rest-api/src/test/java/org/vividus/bdd/steps/integration/ResourceCheckStepsTests.java:201]: I preferred to save my time, feel free to try it out and if it will succeed in 100/100 I'll change it to 1 sec

File: vividus-plugin-html/src/main/java/org/vividus/util/HtmlUtils.java (hunk 1 above)
Comment (uarlouski) [reply vividus-plugin-html/src/main/java/org/vividus/util/HtmlUtils.java:31]: this method reuses parsing and selecting logic in the method below

Comment (uarlouski) [reply vividus-plugin-html/src/main/java/org/vividus/util/HtmlUtils.java:31]: image

**Review by valfirst — APPROVED** [review]

File: vividus-plugin-web-app-to-rest-api/src/test/java/org/vividus/bdd/steps/integration/ResourceCheckStepsTests.java (hunk 8 above)
Comment (ikalinin1) [reply vividus-plugin-web-app-to-rest-api/src/test/java/org/vividus/bdd/steps/integration/ResourceCheckStepsTests.java:201]: But it will make our CI slower

File: docs/modules/plugins/pages/plugin-web-app-to-rest-api.adoc [hunk 11]
```diff
@@ -10,6 +10,39 @@ The plugin provides the integration between web application testing functionalit
...
 
+== Steps
+
+=== Validate resources
+
+Validates resources on web pages
+
+Resource validation logic:
+
+. If the `pages` row contains relative URL then it gets resolved against URL in `web-application.main-page-url` property, i.e. if the main page URL is `https://elderscrolls.bethesda.net/` and relative url is `/skyrim10` the resulting URL will be `https://elderscrolls.bethesda.net/skyrim10`
```
Comment (ikalinin1) [inline docs/modules/plugins/pages/plugin-web-app-to-rest-api.adoc:21]: ralative url -> relative URL

File: docs/modules/plugins/pages/plugin-web-app-to-rest-api.adoc [hunk 12]
```diff
@@ -10,6 +10,39 @@ The plugin provides the integration between web application testing functionalit
...
+. Collect elements by the CSS selector from each page
+. Get either `href` or `src` attribute value from each element, if neither of attributes exist the validation fails
```
Comment (ikalinin1) [inline docs/modules/plugins/pages/plugin-web-app-to-rest-api.adoc:23]: if neither of the attributes exists the validation fails

File: vividus-plugin-html/src/main/java/org/vividus/util/HtmlUtils.java [hunk 13]
```diff
@@ -28,7 +28,12 @@ private HtmlUtils()
...
+    }
+
+    public static Elements getElements(String baseUri, String html, String cssSelector)
```
Comment (ikalinin1) [inline vividus-plugin-html/src/main/java/org/vividus/util/HtmlUtils.java:34]: is this method covered with the unit tests?

**Review by ikalinin1 — APPROVED** [review]
