### PR TITLE
[vividus-plugin-web-app-to-rest-api] Fix StringIndexOutOfBoundsExcept…

### LINKED ISSUE #408: Resource check fails for some URLs due StringIndexOutOfBoundsException
**Describe the bug**
Resource check:
Then all resources by selector `iframe[src*='youtube'], video` from ${pageSource} are valid
Fails when the youtube link contains special symbols.

**To Reproduce**
Try to crowl and check embeded youtube videos:
https://www.youtube.com/embed/N2KtnYLDQ_M?rel=0&showinfo=0;&enablejsapi=1&origin=https%3A%2F%2Fwww.martini.com -- java.lang.StringIndexOutOfBoundsException
https://www.youtube.com/embed/TsPPxK_6Ic4?rel=0&showinfo=0&controls=0&enablejsapi=1&origin=https%3A%2F%2Fwww.bacardi.com --good for recousrce check

**Expected behavior**
Resource check should return expected value (Passed or Failed instead of exception)

**Artifacts**
[log.log](https://github.com/vividus-framework/vividus/files/4356057/log.log)

**Execution environment (please complete the following information):**
 - Vividus version: [e.g. 0.2.0]
 - OS: [e.g. Windows 10]
 - Java: [e.g. jdk-12.0.2]

### PR DESCRIPTION
**Pull request by Ulyana-Yeryksonava**
…ion for empty source in step 'Then all resources by selector `$cssSelector` from $html are valid'

Closes #408

### CODE REVIEW

File: vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/bdd/steps/integration/ResourceCheckSteps.java [hunk 1]
```diff
@@ -119,24 +119,38 @@ private ResourceValidation validate(ResourceValidation r)
         return HtmlUtils.getElements(html, cssSelector).parallelStream();
     }
 
+    private boolean isSourceAttributeEmpty(Element element)
+    {
+        boolean isSourceAttributeEmpty = getElementSourceAttribute(element).isEmpty();
+        if (isSourceAttributeEmpty)
+        {
+            softAssert.recordFailedAssertion(
```
Comment (uarlouski) [inline vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/bdd/steps/integration/ResourceCheckSteps.java]: shouldn't we adjust resource checking logic depending on an element being checked? for examples 'a' element is allowed to be without href attr whereas 'img' isn't
https://www.w3.org/TR/html52/semantics-embedded-content.html#the-img-element
https://www.w3.org/TR/html52/textlevel-semantics.html#the-a-element

File: vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/bdd/steps/integration/ResourceCheckSteps.java [hunk 2]
```diff
@@ -119,24 +119,38 @@ private ResourceValidation validate(ResourceValidation r)
         return HtmlUtils.getElements(html, cssSelector).parallelStream();
     }
 
+    private boolean isSourceAttributeEmpty(Element element)
+    {
+        boolean isSourceAttributeEmpty = getElementSourceAttribute(element).isEmpty();
```
Comment (uarlouski) [inline vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/bdd/steps/integration/ResourceCheckSteps.java]: isSourceAttributeEmpty -> sourceAttributeEmpty

File: vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/bdd/steps/integration/ResourceCheckSteps.java (hunk 1 above)
Comment (Ulyana-Yeryksonava) [reply vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/bdd/steps/integration/ResourceCheckSteps.java]: I suppose it doesn't matter, the only one restriction is: an element must have src or href

File: vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/bdd/steps/integration/ResourceCheckSteps.java (hunk 2 above)
Comment (Ulyana-Yeryksonava) [reply vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/bdd/steps/integration/ResourceCheckSteps.java]: why do you think so? https://rules.sonarsource.com/java/tag/convention/RSPEC-2047

Comment (uarlouski) [reply vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/bdd/steps/integration/ResourceCheckSteps.java]: My comment is related to local var, not to method name

File: vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/bdd/steps/integration/ResourceCheckSteps.java (hunk 1 above)
Comment (uarlouski) [reply vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/bdd/steps/integration/ResourceCheckSteps.java]: I meant why should we fail during resource checking of links if it's not prohibited by spec to have <a> without href?

Comment (Ulyana-Yeryksonava) [reply vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/bdd/steps/integration/ResourceCheckSteps.java]: it causes StringIndexOutOfBoundsException otherwise

File: vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/bdd/steps/integration/ResourceCheckSteps.java [hunk 3]
```diff
@@ -119,24 +119,38 @@ private ResourceValidation validate(ResourceValidation r)
...
+                {
+                    URI toCheck = rv.getUri();
+                    boolean validatable = Optional.ofNullable(toCheck.getScheme()).map(s -> ALLOWED_SCHEMES.contains(s))
+                            .orElse(false) && !excludeHrefsPattern.matcher(rv.toString()).matches();
+                    if (!validatable)
+                    {
+                        rv.setCheckStatus(CheckStatus.FILTERED);
+                    }
+                    return rv;
+                });
```
Comment (valfirst) [inline vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/bdd/steps/integration/ResourceCheckSteps.java]:
```java
private Stream<ResourceValidation> createResourceValidations(Stream<Element> elements,
        Function<Pair<URI, String>, ResourceValidation> resourceValidationFactory)
{
    return elements.map(e ->
        Pair.of(getElementAttribute(e, "href").orElseGet(() -> e.attr("src")).trim(), getSelector(e)))
                   .filter(p -> !p.getKey().isEmpty() || softAssert.recordFailedAssertion(
                    "Element by selector " + p.getValue() + " doesn't contain href/src attributes"))
                   .map(p -> Pair.of(createUri(p.getKey()), p.getValue()))
                   .map(resourceValidationFactory)
                   .peek(rv ->
                   {
                       if (!Optional.ofNullable(rv.getUri().getScheme()).map(ALLOWED_SCHEMES::contains).orElse(false)
                               || excludeHrefsPattern.matcher(rv.toString()).matches())
                       {
                           rv.setCheckStatus(CheckStatus.FILTERED);
                       }
                   });
}

File: vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/bdd/steps/integration/ResourceCheckSteps.java (hunk 1 above)
Comment (uarlouski) [reply vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/bdd/steps/integration/ResourceCheckSteps.java]: thanks for updating the docs :)

File: vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/bdd/steps/integration/ResourceCheckSteps.java [hunk 4]
```diff
@@ -122,21 +123,18 @@ private ResourceValidation validate(ResourceValidation r)
...
+                .filter(p -> !p.getKey().isEmpty() || softAssert.recordFailedAssertion(
+                        "Element by selector " + p.getValue() + " doesn't contain href/src attributes"))
+                .map(p -> Pair.of(createUri(p.getKey()), p.getValue())).map(resourceValidationFactory).peek(rv ->
+                {
+                    if (!Optional.ofNullable(rv.getUri().getScheme()).map(ALLOWED_SCHEMES::contains).orElse(false)
+                            || excludeHrefsPattern.matcher(rv.toString()).matches())
+                    {
+                        rv.setCheckStatus(CheckStatus.FILTERED);
+                    }
+                });
```
Comment (valfirst) [inline vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/bdd/steps/integration/ResourceCheckSteps.java]: please format it properly (you can use my comment unchanged), for example, take a look at `peek` operation it's really hard to find it first of all, and it's hard to track the sequence of actions

File: vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/bdd/steps/integration/ResourceCheckSteps.java [hunk 5]
```diff
@@ -122,21 +123,18 @@ private ResourceValidation validate(ResourceValidation r)
...
-                                                         && !excludeHrefsPattern.matcher(rv.toString()).matches();
-                           if (!validatable)
-                           {
-                               rv.setCheckStatus(CheckStatus.FILTERED);
-                           }
-                           return rv;
-                       });
+        return elements
+                .map(e -> Pair.of(getElementAttribute(e, "href").orElseGet(() -> e.attr("src")).trim(), getSelector(e)))
+                .filter(p -> !p.getKey().isEmpty() || softAssert.recordFailedAssertion(
```
Comment (ikalinin1) [inline vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/bdd/steps/integration/ResourceCheckSteps.java]: Move into separte method
```java
private boolean notEmpty(Pair<String, String>)
{
    return  !p.getKey().isEmpty() || softAssert.recordFailedAssertion("Element by selector " + p.getValue() + " doesn't contain href/src attributes");
}

.filter(this::notEmpty)
```
and use it like:

Comment (valfirst) [reply vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/bdd/steps/integration/ResourceCheckSteps.java]: I would not move it, because logic is tightly coupled ('src', 'href' references)
