### PR TITLE
[plugin-kafka] Support multiple configurations

### LINKED ISSUE #1580: Kafka: Ability to set multiple group ids per single run
Current state: group.id is set on property level and cannot be changed. Tests executed in parallel fail because they consume under same group id.

Example of property: kafka.consumer.group.id=anhelina

Thus in order to run tests in parallel we need to have ability to set multiple group ids per single run.
Ideally it should be implemented as step, to set specific id for corresponding stories/scenarios, but it's just my vision :)

### PR DESCRIPTION
**Pull request by ikalinin1**
Closes #1580

### CODE REVIEW

File: vividus-plugin-kafka/src/main/java/org/vividus/bdd/steps/kafka/KafkaSteps.java [hunk 1]
```diff
@@ -72,57 +77,72 @@
...
+    public void startKafkaListener(String consumerKey, Set<String> topics)
     {
-        stopListener(false);
+        String listenerKey = listenerKey(consumerKey);
+        stopListener(listenerKey, false);
         BlockingQueue<String> messageQueue = new LinkedBlockingDeque<>();
-        testContext.put(MESSAGES_KEY, messageQueue);
-        ContainerProperties containerProperties = new ContainerProperties(topics.toArray(new String[0]));
+        testContext.put(messagesKey(consumerKey), messageQueue);
+        var containerProperties = new ContainerProperties(topics.toArray(new String[0]));
```
Comment (valfirst) [inline vividus-plugin-kafka/src/main/java/org/vividus/bdd/steps/kafka/KafkaSteps.java:139]: I don't think it makes sense to follow SQ warnings like this in the production code

File: vividus-plugin-kafka/src/main/java/org/vividus/bdd/steps/kafka/KafkaSteps.java [hunk 2]
```diff
@@ -184,27 +209,44 @@ public void stopKafkaListener()
...
             String variableName)
     {
-        bddVariableContext.putVariable(scopes, variableName, queueOperation.performOn(testContext.get(MESSAGES_KEY)));
+        bddVariableContext.putVariable(scopes, variableName, queueOperation.performOn(
+                testContext.get(messagesKey(consumerKey))));
+    }
+
+    private String messagesKey(String consumerKey)
+    {
+        return consumerKey + "kafkaMessages";
```
Comment (valfirst) [inline vividus-plugin-kafka/src/main/java/org/vividus/bdd/steps/kafka/KafkaSteps.java:222]: I think the key should be more strict to avoid possible collisions (the best approach is to rely on some class name which is unique in scope of the plugin)

File: vividus-plugin-kafka/src/main/java/org/vividus/bdd/steps/kafka/KafkaSteps.java [hunk 3]
```diff
@@ -184,27 +209,44 @@ public void stopKafkaListener()
...
+    }
+
+    private String listenerKey(String consumerKey)
+    {
+        return consumerKey + KAFKA_LISTENER;
```
Comment (valfirst) [inline vividus-plugin-kafka/src/main/java/org/vividus/bdd/steps/kafka/KafkaSteps.java:227]: the same as for messages key

**Review by valfirst — CHANGES_REQUESTED** [review]

**Review by valfirst — CHANGES_REQUESTED** [review]
And I still think we need some reference to the deprecated properties and steps

File: docs/modules/plugins/pages/plugin-kafka.adoc [hunk 4]
```diff
@@ -10,6 +10,27 @@ The plugin provides integration with an open-source distributed event streaming
 implementation(group: 'org.vividus', name: 'vividus-plugin-kafka', version: '{current-version}')
 ----
 
+== Deprecations
+
+=== Steps
+
+Following list of steps are deprecated and will be removed in the following releases:
```
Comment (valfirst) [inline docs/modules/plugins/pages/plugin-kafka.adoc:17]: `The following list of steps is deprecated and will be removed in the future releases:`

File: docs/modules/plugins/pages/plugin-kafka.adoc [hunk 5]
```diff
@@ -10,6 +10,27 @@ The plugin provides integration with an open-source distributed event streaming
...
+When I send data `$data` to Kafka topic `$topic`
+When I start consuming messages from Kafka topics `$topics`
+When I wait with `$timeout` timeout until count of consumed Kafka messages is $comparisonRule `$expectedCount`
+When I stop consuming messages from Kafka
+When I $queueOperation consumed Kafka messages to $scopes variable `$variableName`
+----
+
+=== Properties
+
+Properties with the following prefixes are deprecated: `kafka.producer.` `kafka.consumer.` and will be removed in the following releases.
```
Comment (valfirst) [inline docs/modules/plugins/pages/plugin-kafka.adoc:30]:
```
The generic (without producer and consumer keys) properties with `kafka.producer.` and `kafka.consumer.` prefixes are deprecated and will be removed in the future releases.
```

File: docs/modules/plugins/pages/plugin-kafka.adoc [hunk 6]
```diff
@@ -10,6 +10,27 @@ The plugin provides integration with an open-source distributed event streaming
...
+
+Documentation for the deprecated properties and steps could be found xref:0.3.4@vividus:plugins:plugin-kafka.adoc[Plugin Kafka 0.3.4]
```
Comment (valfirst) [inline docs/modules/plugins/pages/plugin-kafka.adoc:32]:
```
The documentation for the deprecated steps and properties can be found in ...
```

File: vividus-plugin-kafka/src/main/java/org/vividus/bdd/steps/kafka/KafkaSteps.java [hunk 7]
```diff
@@ -72,57 +82,72 @@
...
         ContainerProperties containerProperties = new ContainerProperties(topics.toArray(new String[0]));
         containerProperties.setMessageListener(
                 (MessageListener<String, String>) data -> messageQueue.add(data.value()));
-        GenericMessageListenerContainer<String, String> container = new KafkaMessageListenerContainer<>(consumerFactory,
-                containerProperties);
+        GenericMessageListenerContainer<String, String> container = new KafkaMessageListenerContainer<>(
+                consumerFactories.get(consumerKey), containerProperties);
         container.start();
-        testContext.put(LISTENER_KEY, container);
+        testContext.put(listenerKey, container);
```
Comment (valfirst) [inline vividus-plugin-kafka/src/main/java/org/vividus/bdd/steps/kafka/KafkaSteps.java:150]:
```java
testContext.get(LISTENER_KEY, HashMap::new).put(consumerKey, container);
```
?

File: vividus-plugin-kafka/src/main/java/org/vividus/bdd/steps/kafka/KafkaSteps.java [hunk 8]
```diff
@@ -72,57 +82,72 @@
...
-    public void startKafkaListener(Set<String> topics)
+    @When("I start consuming messages from `$consumerKey` Kafka topics `$topics`")
+    public void startKafkaListener(String consumerKey, Set<String> topics)
     {
-        stopListener(false);
+        String listenerKey = listenerKey(consumerKey);
+        stopListener(listenerKey, false);
         BlockingQueue<String> messageQueue = new LinkedBlockingDeque<>();
-        testContext.put(MESSAGES_KEY, messageQueue);
+        testContext.put(messagesKey(consumerKey), messageQueue);
```
Comment (valfirst) [inline vividus-plugin-kafka/src/main/java/org/vividus/bdd/steps/kafka/KafkaSteps.java:143]:
```java
testContext.get(MESSAGES_KEY, HashMap::new).put(consumerKey, messageQueue);
```
?

**Review by valfirst — CHANGES_REQUESTED** [review]

**Review by valfirst — APPROVED** [review]

**Review by uarlouski — APPROVED** [review]
