### PR TITLE
[plugin-web-app-to-rest-api] Fix absent query parameters in resolved urls

### LINKED ISSUE #1849: Step "Then all resources by selector `$cssSelector` from ${pageSource} are valid" doesn't check links with parameters
**Describe the bug**
HTML page source contains links with parameters as 'href="/products?categoryId=6596"', and the step  "Then all resources by selector `$cssSelector` from ${pageSource} are valid" don't check the links with parameters and passed without checking the links with parameters (parameters are omitted from the URL during the check)

**To Reproduce**
Scenario: Login to main page
Meta:
    @layout desktop chrome_tablet chrome_phone
Given I login to web application as Beauty Advisor

Scenario: Verify Products links XL
Meta:
    @layout desktop
When I wait until element located `By.xpath(//*[@data-testid='header.navigation.products'])` appears
When I hover a mouse over an element with the xpath '//*[@data-testid='header.navigation.products']'
When I wait until element located `By.xpath(//div[contains(@class,'StyledSpinner')])` disappears
When I wait until element located `By.xpath(//a[contains(@href,'/products?categoryId=3796')])` appears
Then all resources by selector `li>a` from ${pageSource} are valid

**Expected behavior**
Links with parameters are checked

**Artifacts**
Screenshot 2021-08-03 at 16 00 53

**Execution environment (please complete the following information):**
 - Vividus version: 0.3.8-SNAPSHOT
 - OS: MAcOS 11.4
 - Java: JDK 16

**Desktop Web (if applicable, please complete the following information):**
 - Browser Chrome

### PR DESCRIPTION
**Pull request by uarlouski**
Fixes #1849

### CODE REVIEW

**Review by ikalinin1 — APPROVED** [review]

File: vividus-plugin-web-app-to-rest-api/src/test/java/org/vividus/bdd/steps/integration/ResourceCheckStepsTests.java [hunk 1]
```diff
@@ -90,6 +90,10 @@
     private static final URI VIVIDUS_URI = URI.create("https://vividus.org");
     private static final URI VIVIDUS_ABOUT_URI = URI.create("https://vividus.org/about");
     private static final URI SERENITY_URI = URI.create("http://www.thucydides.info");
+    private static final URI VIVIDUS_QUERY_URI_1 = URI.create("https://vividus.org/products?name=pelmeshki");
```
Comment (valfirst) [inline vividus-plugin-web-app-to-rest-api/src/test/java/org/vividus/bdd/steps/integration/ResourceCheckStepsTests.java:93]: 🥟

**Review by valfirst — APPROVED** [review]
