### PR TITLE
[engine] Resolve identical Jbehave story names

### LINKED ISSUE #3607: Stories with the same name but different paths are displayed as one in Allure
**Describe the bug**
Two or more stories with the same name but different locations are displayed as one story in Allure report which include scenarios from all stories with the same name.

By the way JSON test execution results have only one story too.

**To Reproduce**
Run several stories that have the same name but different paths in one batch.

**Expected behavior**
Users should be able to distinguish which scenarios belong to which particular story.

**Artifacts**
[allureReportCollision.zip](https://github.com/vividus-framework/vividus/files/10580404/allureReportCollision.zip)
[storiesCollision.zip](https://github.com/vividus-framework/vividus/files/10580430/storiesCollision.zip)
[jbehaveCollision.zip](https://github.com/vividus-framework/vividus/files/10580482/jbehaveCollision.zip)

Resource settings:
`bdd.story-loader.batch-1.resource-location=story/experimental/StoryNameCollision`
`bdd.story-loader.batch-1.resource-include-patterns=/**/*.story`

### PR DESCRIPTION
**Pull request by draker94**
Closes #3607

### CODE REVIEW

File: vividus-engine/src/main/java/org/vividus/IdenticalStoryNamesResolver.java [hunk 1]
```diff
@@ -0,0 +1,98 @@
...
+    private Path getPathSafely(String path)
+    {
+        try
+        {
+            return Paths.get(path);
+        }
+        catch (InvalidPathException e)
+        {
+            Path resultPath = Paths.get(URI.create(FilenameUtils.getFullPath(path)));
+            return Paths.get(resultPath.toString(), FilenameUtils.getName(path));
```
Comment (valfirst) [inline vividus-engine/src/main/java/org/vividus/IdenticalStoryNamesResolver.java:95]: it make sense to add tests for these code branches if they are relevant, or remove them if irrelevant

Comment (draker94) [reply vividus-engine/src/main/java/org/vividus/IdenticalStoryNamesResolver.java:95]: > it make sense to add tests for these code branches if they are relevant, or remove them if irrelevant

Actually on Windows these case are covered with tests because Windows not allow to use ":" symbol in path and JVM throws `InvalidPathException` instead of Linux from witch we get codecov report
image

**Review by valfirst — CHANGES_REQUESTED** [review]

File: vividus-engine/src/test/java/org/vividus/BatchedPerformableTreeTests.java [hunk 2]
```diff
@@ -89,6 +96,33 @@ void testPerformBeforeOrAfterStoriesPerformNoneForAfter()
...
+        batchedPerformableTree.performBeforeOrAfterStories(runContext, Stage.BEFORE);
+        assertEquals("folder" + File.separator + "name.story", storyFolderName.getName());
+    }
+
+    @Test
+    void shouldNotInteractWithStoriesAfterStories()
+    {
+        PerformableRoot root = batchedPerformableTree.getRoot();
+        Story storyMock = mock(Story.class);
+        PerformableStory performableStoryMock = mock(PerformableStory.class);
```
Comment (valfirst) [inline vividus-engine/src/test/java/org/vividus/BatchedPerformableTreeTests.java:116]:
```suggestion
        Story storyMock = mock();
        PerformableStory performableStoryMock = mock();
```
it can be simplified

Comment (valfirst) [reply vividus-engine/src/test/java/org/vividus/BatchedPerformableTreeTests.java:116]: the same for similar cases

**Review by valfirst — APPROVED** [review]

**Comment by ikalinin1** [comment]
@draker94  please share report example

**Comment by draker94** [comment]
> @draker94 please share report example

@ikalinin1 
[reports3666.zip](https://github.com/vividus-framework/vividus/files/10872932/reports3666.zip)
You can also check new stories from current PR reports

**Comment by ikalinin1** [comment]
> > @draker94 please share report example
> 
> @ikalinin1 [reports3666.zip](https://github.com/vividus-framework/vividus/files/10872932/reports3666.zip) You can also check new stories from the current PR reports

Currently in the report story and the batch definition uses a different path separator, please consider refactoring to have the same separator in both places

image

image

we need to use "/" for consistency in all cases

**Comment by draker94** [comment]
@ikalinin1 
New report with the fix.
In addition, store names are now resolved only relative to the current batch.
[reports3666-1.zip](https://github.com/vividus-framework/vividus/files/10881391/reports3666-1.zip)

File: vividus-engine/src/main/java/org/vividus/IdenticalStoryNamesResolver.java [hunk 3]
```diff
@@ -0,0 +1,104 @@
...
+public class IdenticalStoryNamesResolver
+{
+    private static final char UNIX_PATH_SEPARATOR = '/';
+
+    public void resolveIdenticalNames(List<Story> stories)
+    {
+        for (Story story : stories)
+        {
+            List<Story> sameNameStories = stories.stream()
+                    .filter(s -> story.getName().equals(s.getName())).collect(Collectors.toList());
```
Comment (ikalinin1) [inline vividus-engine/src/main/java/org/vividus/IdenticalStoryNamesResolver.java:39]:
```suggestion
            var storyName = story.getName();
            List<Story> sameNameStories = stories.stream()
                    .filter(s -> storyName.equals(s.getName())).collect(Collectors.toList());
```

Comment (valfirst) [reply vividus-engine/src/main/java/org/vividus/IdenticalStoryNamesResolver.java]: no `var` in production code (yet)

Comment (ikalinin1) [reply vividus-engine/src/main/java/org/vividus/IdenticalStoryNamesResolver.java]: yeah, sorry, just wasn't sure about the type

**Review by ikalinin1 — APPROVED** [review]

**Review by valfirst — APPROVED** [review]
