### PR TITLE
[visual-testing] Fix ignoring for contextual checks

### LINKED ISSUE #1906: Ignoring option does not work for context element for visual checks in mobile
Steps:
1. Change context to an element
2. Try to apply ignoring option to create baseline for context element
Example: 
When I change context to element located `locator`
When I ESTABLISH baseline with `name` ignoring:   
|ELEMENT|                                                         
|By.locator|

**Actual result**: ignoring option does not work, baseline of all context element is created
**Expected result:** baseline of context element with ignoring option should be created

### PR DESCRIPTION
**Pull request by ikalinin1**
Fixes #1906

### CODE REVIEW

File: vividus-extension-visual-testing/src/main/java/org/vividus/visual/screenshot/AdjustingCoordsProvider.java [hunk 1]
```diff
@@ -17,32 +17,29 @@
...
 import org.vividus.selenium.manager.IWebDriverManager;
+import org.vividus.selenium.screenshot.AbstractAdjustingCoordsProvider;
 import org.vividus.selenium.screenshot.IScrollbarHandler;
 import org.vividus.ui.context.IUiContext;
 
 import ru.yandex.qatools.ashot.coordinates.Coords;
-import ru.yandex.qatools.ashot.coordinates.WebDriverCoordsProvider;
 
-public class AdjustingCoordsProvider extends WebDriverCoordsProvider
+public class AdjustingCoordsProvider extends AbstractAdjustingCoordsProvider
```
Comment (valfirst) [inline vividus-extension-visual-testing/src/main/java/org/vividus/visual/screenshot/AdjustingCoordsProvider.java:29]:
```suggestion
public class WebAdjustingCoordsProvider extends AbstractAdjustingCoordsProvider
```
?
and about moving it to `vividus-plugin-web-app`?

File: vividus-extension-selenium/src/main/java/org/vividus/selenium/screenshot/AbstractAdjustingCoordsProvider.java [hunk 2]
```diff
@@ -0,0 +1,51 @@
...
+        if (searchContext instanceof WebElement)
+        {
+            Coords searchContextCoords = coordsProvider.apply((WebElement) searchContext);
+            Coords intersected = coords.intersection(searchContextCoords);
+            intersected.x = intersected.x - searchContextCoords.x;
+            intersected.y = intersected.y - searchContextCoords.y;
+            return intersected;
+        }
+        return coords;
+    }
```
Comment (valfirst) [inline vividus-extension-selenium/src/main/java/org/vividus/selenium/screenshot/AbstractAdjustingCoordsProvider.java:50]:
```suggestion
    protected Coords adjustToSearchContext(Coords coords)
    {
        SearchContext searchContext = uiContext.getSearchContext();
        if (searchContext instanceof WebElement)
        {
            Coords searchContextCoords = getCoords((WebElement) searchContext);
            Coords intersected = coords.intersection(searchContextCoords);
            intersected.x = intersected.x - searchContextCoords.x;
            intersected.y = intersected.y - searchContextCoords.y;
            return intersected;
        }
        return coords;
    }

    protected abstract Coords getCoords(WebElement webElement);
```
?

File: vividus-plugin-mobile-app/src/main/java/org/vividus/selenium/mobileapp/screenshot/NativeHeaderAwareCoordsProvider.java [hunk 3]
```diff
@@ -19,25 +19,39 @@
...
 
     private final transient MobileAppWebDriverManager mobileAppWebDriverManager;
+    private final transient IUiContext uiContext;
 
-    public NativeHeaderAwareCoordsProvider(MobileAppWebDriverManager mobileAppWebDriverManager)
+    public NativeHeaderAwareCoordsProvider(MobileAppWebDriverManager mobileAppWebDriverManager, IUiContext uiContext)
     {
+        super(uiContext);
         this.mobileAppWebDriverManager = mobileAppWebDriverManager;
+        this.uiContext = uiContext;
```
Comment (valfirst) [inline vividus-plugin-mobile-app/src/main/java/org/vividus/selenium/mobileapp/screenshot/NativeHeaderAwareCoordsProvider.java:38]: it's better to introduce `protected` getter in `AbstractAdjustingCoordsProvider `

**Review by valfirst — CHANGES_REQUESTED** [review]

File: vividus-extension-visual-testing/src/main/resources/spring.xml [hunk 4]
```diff
@@ -7,7 +7,7 @@
        default-lazy-init="true">
 
     <beans profile="web">
-        <bean id="coordsProvider" class="org.vividus.visual.screenshot.AdjustingCoordsProvider" />
+        <bean id="coordsProvider" class="org.vividus.visual.screenshot.WebAdjustingCoordsProvider" />
     </beans>
```
Comment (valfirst) [inline vividus-extension-visual-testing/src/main/resources/spring.xml:11]: to move to `vividus-plugin-web-app`?

**Review by valfirst — CHANGES_REQUESTED** [review]

File: vividus-extension-visual-testing/src/main/resources/spring.xml (hunk 4 above)
Comment (ikalinin1) [reply vividus-extension-visual-testing/src/main/resources/spring.xml:11]: I would not to, because now it is used only inside visual testing module

**Review by valfirst — APPROVED** [review]

File: vividus-plugin-mobile-app/src/main/java/org/vividus/selenium/mobileapp/screenshot/NativeHeaderAwareCoordsProvider.java [hunk 5]
```diff
@@ -19,25 +19,37 @@
...
+        super(uiContext);
         this.mobileAppWebDriverManager = mobileAppWebDriverManager;
     }
 
     @Override
     public Coords ofElement(WebDriver driver, WebElement element)
     {
-        Coords coords = super.ofElement(driver, element);
+        Coords coords = getCoords(element);
+        if (getUiContext().getSearchContext() != element)
```
Comment (uarlouski) [inline vividus-plugin-mobile-app/src/main/java/org/vividus/selenium/mobileapp/screenshot/NativeHeaderAwareCoordsProvider.java:43]: let's try ternary to avoid unnecessary assignment?
