### PR TITLE
[web-app] Throw user-friendly error when missing main application page URL is used

### LINKED ISSUE #784: It is impossible to run stories if one story is set to be skipped where main page url is missing in properties
**To Reproduce**
Scenario: browsers, platforms
Meta:
@skip
@layout desktop chrome_phone phone
When I go to the relative URL '${authority}<rel-url>'
When I ${visual-action} baseline with `${brand}#{eval(`<rel-url>`.replaceAll(`/`,`-`))}-${profile}`
Examples:
{transformer=FROM_SITEMAP, siteMapRelativeUrl=/sitemap.xml, ignoreErrors=true, column=rel-url}
{transformer=FILTERING, byMaxRows=5}

**Actual**
java.lang.NullPointerException
	at org.vividus.util.UriUtils.buildNewUrl(UriUtils.java:235)
	at org.vividus.util.UriUtils.buildNewRelativeUrl(UriUtils.java:277)
	at org.vividus.sitemap.SiteMapParser.buildSiteMapUrl(SiteMapParser.java:121)
	at org.vividus.sitemap.SiteMapParser.parse(SiteMapParser.java:107)
	at org.vividus.transformer.SiteMapTableTransformer.lambda$fetchUrls$1(SiteMapTableTransformer.java:61)
	at java.base/java.util.Optional.orElseGet(Optional.java:362)
	at org.vividus.transformer.SiteMapTableTransformer.fetchUrls(SiteMapTableTransformer.java:56)
	at org.vividus.transformer.AbstractFetchingUrlsTableTransformer.transform(AbstractFetchingUrlsTableTransformer.java:50)
	at org.jbehave.core.model.TableTransformers.transform(TableTransformers.java:45)
	at org.jbehave.core.model.ExamplesTable.applyTransformers(ExamplesTable.java:229)
	at org.jbehave.core.model.ExamplesTable.<init>(ExamplesTable.java:207)
	at org.jbehave.core.model.ExamplesTableFactory.createExamplesTable(ExamplesTableFactory.java:86)
	at org.jbehave.core.parsers.RegexStoryParser.parseExamplesTable(RegexStoryParser.java:352)
	at org.jbehave.core.parsers.RegexStoryParser.parseScenario(RegexStoryParser.java:313)
	at org.jbehave.core.parsers.RegexStoryParser.parseScenariosFrom(RegexStoryParser.java:290)
	at org.jbehave.core.parsers.RegexStoryParser.parseStory(RegexStoryParser.java:89)
	at org.jbehave.core.embedder.PerformableTree.storyOfPath(PerformableTree.java:331)
	at org.jbehave.core.embedder.StoryManager.storyOfPath(StoryManager.java:61)
	at org.jbehave.core.embedder.StoryManager.storiesOfPaths(StoryManager.java:67)
	at com.github.valfirst.jbehave.junit.monitoring.JUnitReportingRunner.createPerformableTree(JUnitReportingRunner.java:136)
	at com.github.valfirst.jbehave.junit.monitoring.JUnitReportingRunner.buildDescriptionFromStories(JUnitReportingRunner.java:122)
	at com.github.valfirst.jbehave.junit.monitoring.JUnitReportingRunner.<init>(JUnitReportingRunner.java:42)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:37)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
	at org.junit.internal.requests.ClassRequest.createRunner(ClassRequest.java:28)
	at org.junit.internal.requests.MemoizingRequest.getRunner(MemoizingRequest.java:19)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createUnfilteredTest(JUnit4TestLoader.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createTest(JUnit4TestLoader.java:76)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.loadTests(JUnit4TestLoader.java:49)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:526)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

### PR DESCRIPTION
**Pull request by TatianaTochko**
Fixes #784

### CODE REVIEW

File: vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/transformer/SiteMapTableTransformer.java [hunk 1]
```diff
@@ -58,10 +58,17 @@
...
+                    if (mainApplicationPage != null)
+                    {
+                        siteMapRelativeUrls = filterResults(siteMapParser.parse(true, mainApplicationPage,
                             siteMapRelativeUrl).stream()
                             .map(SiteMapURL::getUrl)
                             .map(URL::toString));
+                    }
+                    else
+                    {
+                        throw new IllegalArgumentException("URL of the main application page should be non-blank");
```
Comment (valfirst) [inline vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/transformer/SiteMapTableTransformer.java:70]: unit tests ?

Comment (valfirst) [inline vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/transformer/SiteMapTableTransformer.java:70]: use `org.apache.commons.lang3.Validate` instead

Comment (ikalinin1) [inline vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/transformer/SiteMapTableTransformer.java:70]: Please update:

- Unit tests
- Transformer documentation
- Add property name into message

**Review by ikalinin1 — CHANGES_REQUESTED** [review]

File: vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/transformer/SiteMapTableTransformer.java [hunk 2]
```diff
@@ -58,10 +58,17 @@
                 Set<String> siteMapRelativeUrls;
                 try
                 {
-                    siteMapRelativeUrls = filterResults(siteMapParser.parse(true, mainApplicationPage,
+                    if (mainApplicationPage != null)
```
Comment (valfirst) [inline vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/transformer/SiteMapTableTransformer.java:61]: also I believe the fix should be implemented in `getMainApplicationPageUri()` to avoid the same issue in `HeadlessCrawlerTableTransformer`

**Review by valfirst — CHANGES_REQUESTED** [review]

File: vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/transformer/SiteMapTableTransformer.java (hunk 1 above)
Comment (ikalinin1) [reply vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/transformer/SiteMapTableTransformer.java:70]: How does `org.vividus.transformer.HeadlessCrawlerTableTransformer` works without main page URL?

File: docs/modules/plugins/pages/plugin-web-app-to-rest-api.adoc [hunk 3]
```diff
@@ -92,3 +92,5 @@ Examples:
 Examples:
 {transformer=FROM_HEADLESS_CRAWLING, column=page-url}
 ----
+==== Required envinroment properties
+* `web-application.main-page-url` - defines main application page name
```
Comment (valfirst) [inline docs/modules/plugins/pages/plugin-web-app-to-rest-api.adoc:96]: 1. Put this info before the example
1. Add this info to each affected table transformer

File: docs/modules/plugins/pages/plugin-web-app-to-rest-api.adoc [hunk 4]
```diff
@@ -92,3 +92,5 @@ Examples:
 Examples:
 {transformer=FROM_HEADLESS_CRAWLING, column=page-url}
 ----
+==== Required envinroment properties
```
Comment (valfirst) [inline docs/modules/plugins/pages/plugin-web-app-to-rest-api.adoc:95]: `Required envinroment properties`-> `Required properties`

File: vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/transformer/AbstractFetchingUrlsTableTransformer.java [hunk 5]
```diff
@@ -109,7 +111,9 @@ public void setHttpRedirectsProvider(HttpRedirectsProvider httpRedirectsProvider
 
     protected URI getMainApplicationPageUri()
     {
-        return webApplicationConfiguration.getMainApplicationPageUrl();
+        URI mainApplicationPageUrl = webApplicationConfiguration.getMainApplicationPageUrl();
+        isTrue(mainApplicationPageUrl != null, "URL of the main application page should be non-blank");
+        return mainApplicationPageUrl;
```
Comment (valfirst) [inline vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/transformer/AbstractFetchingUrlsTableTransformer.java:116]: I believe there is no reason to check the value each time the method invoked, consider caching the result (`Suppliers.memoize`?)

**Review by valfirst — CHANGES_REQUESTED** [review]

File: docs/modules/plugins/pages/plugin-web-app-to-rest-api.adoc [hunk 6]
```diff
@@ -48,7 +48,8 @@ implementation(group: 'org.vividus', name: 'vividus-plugin-web-app-to-rest-api',
 |`false`
 |defines whether urls that has redirect to the one that has already been included in the table are excluded from the table
 |===
-
+==== Required properties
+* `web-application.main-page-url` - defines main application page name
```
Comment (valfirst) [inline docs/modules/plugins/pages/plugin-web-app-to-rest-api.adoc:52]: `name` -> `URL`

File: docs/modules/plugins/pages/plugin-web-app-to-rest-api.adoc [hunk 7]
```diff
@@ -86,9 +87,12 @@ Examples:
...
 |===
+==== Required properties
+* `web-application.main-page-url` - defines main application page name
 
 .Usage example
 ----
 Examples:
 {transformer=FROM_HEADLESS_CRAWLING, column=page-url}
 ----
+
```
Comment (valfirst) [inline docs/modules/plugins/pages/plugin-web-app-to-rest-api.adoc:98]: useless change

**Review by valfirst — CHANGES_REQUESTED** [review]

**Review by valfirst — APPROVED** [review]

**Review by uarlouski — APPROVED** [review]

File: vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/transformer/AbstractFetchingUrlsTableTransformer.java [hunk 8]
```diff
@@ -42,6 +47,12 @@
     private WebApplicationConfiguration webApplicationConfiguration;
     private HttpRedirectsProvider httpRedirectsProvider;
     private boolean filterRedirects;
+    private final Supplier<URI> mainApplicationPageUriSupplier = Suppliers.memoize(() ->
+    {
+        URI mainApplicationPageUrl = webApplicationConfiguration.getMainApplicationPageUrl();
```
Comment (ikalinin1) [inline vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/transformer/AbstractFetchingUrlsTableTransformer.java:52]: Could you please refactor to check in one place?
We have a similar check here: https://github.com/vividus-framework/vividus/blob/master/vividus-plugin-web-app/src/main/java/org/vividus/bdd/steps/ui/web/PageSteps.java#L92-L99

**Review by ikalinin1 — CHANGES_REQUESTED** [review]

File: vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/transformer/AbstractFetchingUrlsTableTransformer.java (hunk 8 above)
Comment (TatianaTochko) [reply vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/transformer/AbstractFetchingUrlsTableTransformer.java:52]: resolve this

File: vividus-plugin-web-app/src/main/resources/properties/profile/web/profile.properties [hunk 9]
```diff
@@ -37,7 +37,7 @@ environment-configurer.profile.proxy=#{${proxy.enabled} ? 'ON' : 'OFF'}
 system.wdm.gitHubTokenName=Vividus WebDriverManager
 system.wdm.gitHubTokenSecret=4733c6adb72f077770a72774c012b070ad4e37eb
 
-web-application.main-page-url=
+web-application.main-page-url=https://example.org/
```
Comment (valfirst) [inline vividus-plugin-web-app/src/main/resources/properties/profile/web/profile.properties:40]: invalid change

File: vividus-plugin-web-app/src/main/java/org/vividus/ui/web/configuration/WebApplicationConfiguration.java [hunk 10]
```diff
@@ -29,11 +34,18 @@
...
     public WebApplicationConfiguration(String mainApplicationPageUrlString, AuthenticationMode authenticationMode)
     {
         configurationStorage = ThreadLocal.withInitial(() ->
             new ConfigurationStorage(mainApplicationPageUrlString, authenticationMode));
+        mainApplicationPageUriSupplier = Suppliers.memoize(() ->
+        {
+            URI mainApplicationPageUrl = configurationStorage.get().getMainApplicationPageUri();
+            isTrue(mainApplicationPageUrl != null, "URL of the main application page should be non-blank");
+            return mainApplicationPageUrl;
+        });
```
Comment (valfirst) [inline vividus-plugin-web-app/src/main/java/org/vividus/ui/web/configuration/WebApplicationConfiguration.java:48]: it won't work in this way, because Supplier is shared across threads now, but configuration storage is not, it may lead to wrong URL returned from the cache

File: vividus-plugin-web-app-to-rest-api/src/test/java/org/vividus/bdd/steps/integration/ResourceCheckStepsTests.java [hunk 11]
```diff
@@ -336,10 +327,10 @@ void shouldFilterResourceByRegExpCheckDesiredResourcesAnPostAttachment()
     {
         mockResourceValidator();
         runExecutor();
-        mockWebApplicationConfiguration();
+        //mockWebApplicationConfiguration();
```
Comment (valfirst) [inline vividus-plugin-web-app-to-rest-api/src/test/java/org/vividus/bdd/steps/integration/ResourceCheckStepsTests.java:330]: to remove?

File: vividus-plugin-web-app/src/main/java/org/vividus/ui/web/configuration/WebApplicationConfiguration.java [hunk 12]
```diff
@@ -128,7 +139,7 @@ public void setApplicationEnvironmentType(String applicationEnvironmentType)
 
         private URI getMainApplicationPageUri()
         {
-            return mainApplicationPageUri;
+            return Optional.ofNullable(mainApplicationPageUriSupplier.get()).get();
```
Comment (valfirst) [inline vividus-plugin-web-app/src/main/java/org/vividus/ui/web/configuration/WebApplicationConfiguration.java:142]: ` return mainApplicationPageUriSupplier.get()` ?

**Review by valfirst — CHANGES_REQUESTED** [review]

**Review by valfirst — APPROVED** [review]

**Review by ikalinin1 — APPROVED** [review]

**Review by uarlouski — APPROVED** [review]
