### PR TITLE
[vividus] Introduce configuration sets

### LINKED ISSUE #2462: Configurations sets
In order to simplify the management of multiple configuration sets in the same project, we need to introduce a mechanism to 'switch' active configuration.

For an example currently it could be solved via comments:

#### **`configuration.properties`**
```properties
## Android/Staging/Smoke
configuration.profiles=mobile_app/android
configuration.environments=staging
configuration.suites=smoke

## iOS/Regression/Prod
#configuration.profiles=mobile_app/ios
#configuration.environments=prod
#configuration.suites=regression
```

To simplify this we might support 'active' configuraiton
#### **`configuration-android-smoke-staging.properties`**
```properties
configuration.profiles=mobile_app/android
configuration.environments=staging
configuration.suites=smoke
```

#### **`configuration-ios-regression-prod.properties`**
```properties
configuration.profiles=mobile_app/ios
configuration.environments=prod
configuration.suites=regression
```

User will specify via test run arguments active configuration file, for example, `ios-regression-prod` will point VIVIDUS to load  `configuration-ios-regression-prod.properties` configuration file.

### PR DESCRIPTION
**Pull request by ikalinin1**
Closes #2462

image
image

### CODE REVIEW

File: vividus/src/main/java/org/vividus/configuration/ConfigurationResolver.java [hunk 1]
```diff
@@ -208,6 +209,48 @@ private static Multimap<String, String> assembleConfiguration(Properties configu
         return configuration;
     }
 
+    private static Map<String, String> resolveConfiguration(Properties configurationProperties,
```
Comment (uarlouski) [inline vividus/src/main/java/org/vividus/configuration/ConfigurationResolver.java:212]: won't the code look better if we use POJO to group profiles, envs and suites?

File: vividus-reporter/src/main/java/org/vividus/reporter/environment/PropertyCategory.java [hunk 2]
```diff
@@ -1,5 +1,5 @@
 /*
- * Copyright 2019-2020 the original author or authors.
+ * Copyright 2019-2023 the original author or authors.
```
Comment (uarlouski) [inline vividus-reporter/src/main/java/org/vividus/reporter/environment/PropertyCategory.java:2]: :)

File: vividus/src/main/java/org/vividus/configuration/ConfigurationResolver.java [hunk 3]
```diff
@@ -237,26 +280,33 @@ private static Map<String, String> loadFilteredSystemProperties()
...
+        return value;
+    }
+
+    private static String getPropertyValue(Properties configurationProperties,
+            Properties overridingProperties, String key)
+    {
+        String value = System.getProperty(VIVIDUS_SYSTEM_PROPERTY_FAMILY + key,
                 System.getProperty(VIVIDUS_SYSTEM_PROPERTY_FAMILY + key,
-                        System.getProperty(propertyName, System.getProperty(key))));
+                        System.getProperty(key, System.getProperty(key))));
```
Comment (uarlouski) [inline vividus/src/main/java/org/vividus/configuration/ConfigurationResolver.java:294]: imho propertyName is not so bad to rename it

File: vividus/src/main/java/org/vividus/configuration/ConfigurationResolver.java [hunk 4]
```diff
@@ -237,26 +280,33 @@ private static Map<String, String> loadFilteredSystemProperties()
...
         if (value == null)
         {
-            value = overridingProperties.getProperty(propertyName);
+            value = overridingProperties.getProperty(key);
             if (value == null)
             {
-                value = configurationProperties.getProperty(propertyName);
+                value = configurationProperties.getProperty(key);
                 if (value == null)
```
Comment (valfirst) [inline vividus/src/main/java/org/vividus/configuration/ConfigurationResolver.java:301]: this `if` can be removed now

**Review by valfirst — CHANGES_REQUESTED** [review]

File: vividus/src/main/java/org/vividus/configuration/ConfigurationResolver.java (hunk 1 above)
Comment (ikalinin1) [reply vividus/src/main/java/org/vividus/configuration/ConfigurationResolver.java:212]: I don't think so, take a look at the assembelConfiguraiton method

File: docs/modules/ROOT/pages/tests-configuration.adoc [hunk 5]
```diff
@@ -204,6 +204,36 @@ configuration.environments=dev
...
+configuration-set.api-test-regression.environments=test
+----
+
+Once configuration sets are defined, one can use an active configuration set for test execution.
+
+.Usage of configuration set
+[source,properties]
+----
+configuration-set.active=api-preprod-uat
+#configuration-set.active=api-test-regression
```
Comment (valfirst) [inline docs/modules/ROOT/pages/tests-configuration.adoc:229]: let's remove the comment to avoid ambiguity

File: docs/modules/ROOT/pages/tests-configuration.adoc [hunk 6]
```diff
@@ -204,6 +204,36 @@ configuration.environments=dev
...
+----
+
+IMPORTANT: Configuration sets can be defined only in `configuration.properties` file.
+
+WARNING: Active configuraiton set overrides defined `configuration.profiles`, `configuration.suites` and `configuration.environments` properties.
+
+IMPORTANT: Configuration set requires to define `profiles`, `suites` and `environments`, empty value considered as a valid one.
```
Comment (valfirst) [inline docs/modules/ROOT/pages/tests-configuration.adoc:236]:
```suggestion
[IMPORTANT]
====
* Configuration sets can be defined only in `configuration.properties` file.
* Active configuration set overrides defined `configuration.profiles`, `configuration.suites` and `configuration.environments` properties.
* Configuration set requires to define `profiles`, `suites` and `environments`, empty value considered as a valid one.
====

```

File: vividus/src/test/java/org/vividus/log/TestInfoLoggerTests.java [hunk 7]
```diff
@@ -120,8 +123,24 @@ private static Stream<Arguments> sourceOfFailures()
...
+    @SuppressWarnings({ "MultipleStringLiterals", "MultipleStringLiteralsExtended", "PMD.AvoidDuplicateLiterals"})
+    void shouldLogMetadataWithConfigurationSet()
+    {
+        EnvironmentConfigurer.ENVIRONMENT_CONFIGURATION.get(PropertyCategory.CONFIGURATION).put("Set", "active");
+        shouldLogMetadata(" Configuration set:\\s+active\\s+", "", Optional.empty());
+    }
+
+    @SuppressWarnings({ "MultipleStringLiterals", "MultipleStringLiteralsExtended", "PMD.AvoidDuplicateLiterals"})
+    void shouldLogMetadata(String configurationLine,
+        String failuresMessage, Optional<List<Failure>> failures)
```
Comment (valfirst) [inline vividus/src/test/java/org/vividus/log/TestInfoLoggerTests.java:143]:
```suggestion
    void shouldLogMetadata(String configurationLine, String failuresMessage, Optional<List<Failure>> failures)
```

File: vividus/src/test/java/org/vividus/log/TestInfoLoggerTests.java [hunk 8]
```diff
@@ -131,39 +150,39 @@ void shouldLogMetadata(String failuresMessage, Optional<List<Failure>> failures)
         var statisticsProvider = mock(ResultsProvider.class);
         when(statisticsProvider.getStatistics()).thenReturn(
                 Map.of(ExecutableEntity.STORY, statistic,
-                       ExecutableEntity.SCENARIO, statistic,
-                       ExecutableEntity.STEP, statistic)
+                        ExecutableEntity.SCENARIO, statistic,
+                        ExecutableEntity.STEP, statistic)
```
Comment (valfirst) [inline vividus/src/test/java/org/vividus/log/TestInfoLoggerTests.java:154]: noisy changes

**Review by valfirst — CHANGES_REQUESTED** [review]

**Review by valfirst — APPROVED** [review]
