### PR TITLE
[plugin-web-app] Extract device-pixel-ratio automatically

### LINKED ISSUE #71: Screenshooting mechanism works wrong on MacOS
1. Run Visual check OR force test failure on MacOS
2. Open Allure report -> find a screenshot

Result: Only part of the screen is shown at the screenshot

Expected Result: Entire screen on desired Context should be shown. Please see attached Allure report
[allure.zip](https://github.com/vividus-framework/vividus/files/3591279/allure.zip)

### PR DESCRIPTION
**Pull request by valfirst**
Fixes #71

### CODE REVIEW

File: vividus-plugin-web-app/src/test/java/org/vividus/ui/web/RuntimeEnvironmentTests.java [hunk 1]
```diff
@@ -17,38 +17,55 @@
...
     }
 
     @Test
-    void testGetUserAgentMultipleCalls()
+    void testGetUserAgentMultipleTimes()
     {
         runtimeConfiguration.getUserAgent();
         runtimeConfiguration.getUserAgent();
-        Mockito.verify(jsActions).getUserAgent();
+        verify(javascriptActions, times(1)).getUserAgent();
```
Comment (uarlouski) [inline vividus-plugin-web-app/src/test/java/org/vividus/ui/web/RuntimeEnvironmentTests.java]: times(1) - no need?

File: vividus-plugin-web-app/src/main/java/org/vividus/ui/web/RuntimeEnvironment.java [hunk 2]
```diff
@@ -16,19 +16,30 @@
...
 package org.vividus.ui.web;
 
-import javax.inject.Inject;
-
 import org.vividus.ui.web.action.IJavascriptActions;
 
 public class RuntimeEnvironment implements IRuntimeEnvironment
 {
-    @Inject private IJavascriptActions javascriptActions;
+    private IJavascriptActions javascriptActions;
```
Comment (uarlouski) [inline vividus-plugin-web-app/src/main/java/org/vividus/ui/web/RuntimeEnvironment.java]: might be final now

File: vividus-plugin-web-app/src/main/java/org/vividus/selenium/screenshot/AshotFactory.java [hunk 3]
```diff
@@ -37,37 +41,35 @@
...
     @Inject private IJavascriptActions javascriptActions;
+    @Inject private IRuntimeEnvironment runtimeEnvironment;
     @Inject private ScreenshotDebugger screenshotDebugger;
 
-    public void init()
-    {
-        baseShootingStrategy = ShootingStrategies.scaling((float) webDriverManager.getDevicePixelRatio());
-    }
+    private Supplier<ShootingStrategy> baseShootingStrategy = Suppliers.memoize(
+        () -> ShootingStrategies.scaling((float) runtimeEnvironment.getDevicePixelRatio()));
```
Comment (uarlouski) [inline vividus-plugin-web-app/src/main/java/org/vividus/selenium/screenshot/AshotFactory.java]: is there any chance that we get bad scaling results because we convert double-precision value (as DPR stored and returned by invocation window.devicepixelratio) to single precision value?

File: vividus-plugin-web-app/src/main/java/org/vividus/ui/web/RuntimeEnvironment.java (hunk 2 above)
Comment (valfirst) [reply vividus-plugin-web-app/src/main/java/org/vividus/ui/web/RuntimeEnvironment.java]: it can't be since it's used in `ThreadLocal` fields initialization

File: vividus-plugin-web-app/src/test/java/org/vividus/ui/web/RuntimeEnvironmentTests.java (hunk 1 above)
Comment (valfirst) [reply vividus-plugin-web-app/src/test/java/org/vividus/ui/web/RuntimeEnvironmentTests.java]: I'd like to keep it explicit to emphasize that exactly one invocation is expected, that's important in this test

File: vividus-plugin-web-app/src/main/java/org/vividus/selenium/screenshot/AshotFactory.java (hunk 3 above)
Comment (valfirst) [reply vividus-plugin-web-app/src/main/java/org/vividus/selenium/screenshot/AshotFactory.java]: I've tested and haven't faced with such problem, even more for now there is no case when DPR is actually floating point number, it's always integer

Comment (ikalinin1) [reply vividus-plugin-web-app/src/main/java/org/vividus/selenium/screenshot/AshotFactory.java]: By the way, looks like it's can be floating point https://www.mydevice.io/
