### PR TITLE
[vividus-extension-selenium] Add validate for visibility parameters in step checking state of elements

### LINKED ISSUE #2640: "Verify elements state" step is not verifying elements state nor finding said elements
**Describe the bug**
Step "Then number of not_visible elements found by `$locator` is $comparisonRule `$quantity`" does not find invisible elements. It fails despite the fact that source code has necessary amount of elements in required state.

**Expected behavior**
Step "Then number of not_visible elements found by `$locator` is $comparisonRule `$quantity`" finds required elements and verifies that it's invisible. After that it passes.

**Artifacts**
Failed step in Allure:
image
Part of the application source code that contains invisible elements:
image

**Execution environment:**
 - Vividus version: 0.4.4
 - OS: macOS Monterey 12.3
 - Java: HotSpot(TM) 64-Bit Server VM (build 17.0.2+8-LTS-86, mixed mode, sharing)

**Mobile Web:**
 - Real Device
 - Device: Apple TV (4th generation)
 - OS: tvOS 15.2

### PR DESCRIPTION
**Pull request by draker94**
Relates #2640

### CODE REVIEW

File: vividus-extension-selenium/src/test/java/org/vividus/steps/ui/GenericElementStepsTests.java [hunk 1]
```diff
@@ -107,6 +109,29 @@ void shouldThrowAnExceptionIfLocatorVisibilityAndStateToCheckAreTheSame(Visibili
                 visibility, state), iae.getMessage());
     }
 
+    @ParameterizedTest
+    @CsvSource({ "VISIBLE, NOT_VISIBLE",
+                 "INVISIBLE, VISIBLE" })
+    void shouldThrowAnExceptionIfLocatorVisibilityAndStateToCheckAreDifferent(Visibility visibility, State state)
+    {
+        Locator locator = getLocatorWithVisibility(visibility);
+        IllegalArgumentException iae = assertThrows(IllegalArgumentException.class,
```
Comment (valfirst) [inline vividus-extension-selenium/src/test/java/org/vividus/steps/ui/GenericElementStepsTests.java:118]: not critical, just a hint: you can use `var` keyword in unit tests:
```suggestion
        var illegalArgumentException = assertThrows(IllegalArgumentException.class,
```

**Comment by valfirst** [comment]
Please fix PMD violations

**Review by uarlouski — APPROVED** [review]

File: vividus-extension-selenium/src/main/java/org/vividus/steps/ui/GenericElementSteps.java [hunk 2]
```diff
@@ -95,9 +94,17 @@ public List<WebElement> assertElementsNumber(Locator locator, ComparisonRule com
     public void assertElementsNumberInState(State state, Locator locator, ComparisonRule comparisonRule, int quantity)
     {
         Visibility visibility = locator.getSearchParameters().getVisibility();
-        Validate.isTrue(state != visibility.getState(),
-            "Locator visibility: %s and the state: %s to validate are the same."
-            + " This makes no sense. Please consider validation of elements size instead.", visibility, state);
+        if (visibility != Visibility.ALL && (state == State.VISIBLE || state == State.NOT_VISIBLE))
```
Comment (ikalinin1) [inline vividus-extension-selenium/src/main/java/org/vividus/steps/ui/GenericElementSteps.java:97]: Could you please update javadoc and the docs?

**Review by valfirst — APPROVED** [review]

**Review by ikalinin1 — APPROVED** [review]

**Review by uarlouski — APPROVED** [review]
