### PR TITLE
[vividus] Expand Lists with single element at comparison against table

### LINKED ISSUE #1388: Step "Then `$variable` is equal to table ignoring extra columns:$table" fails with an error
**Describe the bug**
Steps:
When I capture HTTP GET or POST request with URL pattern `${event-url-pattern}<event>.*` and save URL query to scenario variable `request-params`
Then `${request-params}` is equal to table ignoring extra columns:
{headerSeparator=!,valueSeparator=!}
!c22    !c52    !
!Download > Other > SZ Caregiver Doctor Discussion Guide !Body !

an error:
issue

Worked fine on VIVIDUS 0.2.12 and earlier.

**To Reproduce**
run steps:
Given I am on a page with the URL '${authority}<relative_url>'
When I click on element located `By.cssSelector(<click-locator>)`
When I wait until HTTP GET or POST request with URL pattern `${event-url-pattern}<event>.*` exists in proxy log
When I capture HTTP GET or POST request with URL pattern `${event-url-pattern}<event>.*` and save URL query to scenario variable `request-params`
Then `${request-params}` is equal to table ignoring extra columns:
{headerSeparator=!,valueSeparator=!}
{headerSeparator=!,valueSeparator=!}
!c22    !c52    !
!Download > Other > SZ Caregiver Doctor Discussion Guide !Body !

**Expected behavior**
No error in the last step

### PR DESCRIPTION
**Pull request by valfirst**
Closes #1388

### CODE REVIEW

File: vividus/src/main/java/org/vividus/bdd/steps/BddVariableSteps.java [hunk 1]
```diff
@@ -177,18 +180,41 @@ public boolean compareVariables(Object variable1, ComparisonRule condition, Obje
...
+    @SuppressWarnings("unchecked")
     public void tablesAreEqualIgnoringExtraColumns(Object variable, ExamplesTable table)
     {
-        if (!(variable instanceof Map))
-        {
-            throw new IllegalArgumentException("'variable' should be instance of map");
-        }
-        Map<String, String> expectedMap = MapUtils.convertSingleRowExamplesTableToMap(table);
-        List<EntryComparisonResult> results = ComparisonUtils.checkMapContainsSubMap((Map<?, ?>) variable, expectedMap);
+        isTrue(variable instanceof Map, "'variable' should be instance of map");
```
Comment (uarlouski) [inline vividus/src/main/java/org/vividus/bdd/steps/BddVariableSteps.java:186]: out of scope but maybe The 'variable' ...

File: vividus/src/main/java/org/vividus/bdd/steps/BddVariableSteps.java [hunk 2]
```diff
@@ -177,18 +180,41 @@ public boolean compareVariables(Object variable1, ComparisonRule condition, Obje
...
+        Map<Object, Object> actualMap = expandListValuesWithSingleElement((Map<Object, Object>) variable);
+
+        List<Parameters> rows = table.getRowsAsParameters(true);
+        isTrue(rows.size() == 1, "ExamplesTable should contain single row with values");
```
Comment (uarlouski) [inline vividus/src/main/java/org/vividus/bdd/steps/BddVariableSteps.java:190]: Why not just table? This sounds like a end-user term whereas ExamplesTable is a class name/developer term

File: vividus/src/main/java/org/vividus/bdd/steps/BddVariableSteps.java (hunk 1 above)
Comment (valfirst) [reply vividus/src/main/java/org/vividus/bdd/steps/BddVariableSteps.java:186]: you can consult experts 😄  but AFAIK `'variable'` is a name of the input parameter, so it doesn't require articles

File: vividus/src/main/java/org/vividus/bdd/steps/BddVariableSteps.java [hunk 3]
```diff
@@ -177,18 +180,41 @@ public boolean compareVariables(Object variable1, ComparisonRule condition, Obje
...
+
+        Map<String, String> expectedMap =  rows.get(0).values();
+        List<EntryComparisonResult> results = ComparisonUtils.checkMapContainsSubMap(actualMap, expectedMap);
         publishMapComparisonResults(List.of(results));
         softAssert.assertTrue(TABLES_ARE_EQUAL, results.stream().allMatch(EntryComparisonResult::isPassed));
     }
 
+    private Map<Object, Object> expandListValuesWithSingleElement(Map<Object, Object> map)
```
Comment (uarlouski) [inline vividus/src/main/java/org/vividus/bdd/steps/BddVariableSteps.java:198]: if we have 10 entries in the map where first 9 entries have a value List with size 1, but the last one is different, we will eventually return the map passed as param and put operation on expandedMap will be redundant, so does it make sense to check first that the input map has list with size 1? (for example via allMatch)

File: vividus/src/main/java/org/vividus/bdd/steps/BddVariableSteps.java (hunk 2 above)
Comment (valfirst) [reply vividus/src/main/java/org/vividus/bdd/steps/BddVariableSteps.java:190]: ExamplesTable is a part of JBehave terminology, tcase/whitespaces are discussable, but there should be clear ExamplesTable reference

File: vividus/src/main/java/org/vividus/bdd/steps/BddVariableSteps.java (hunk 3 above)
Comment (valfirst) [reply vividus/src/main/java/org/vividus/bdd/steps/BddVariableSteps.java:198]: in this way it'll be required to traverse the map twice and execute similar logic, if you'd like, you can create a benchmark

File: vividus/src/main/java/org/vividus/bdd/steps/BddVariableSteps.java (hunk 2 above)
Comment (uarlouski) [reply vividus/src/main/java/org/vividus/bdd/steps/BddVariableSteps.java:190]: End user can guess that we use JBehave only by plugin installed in eclipse, should not we advice end users somewhere in the docs to get acquainted with JBehave by giving some links?

File: vividus/src/main/java/org/vividus/bdd/steps/BddVariableSteps.java (hunk 3 above)
Comment (uarlouski) [reply vividus/src/main/java/org/vividus/bdd/steps/BddVariableSteps.java:198]: even if we imagine we have a dataset where the double for is slower it's a bit weird to populate map that is potentially will never be used

File: vividus/src/main/java/org/vividus/bdd/steps/BddVariableSteps.java (hunk 2 above)
Comment (valfirst) [reply vividus/src/main/java/org/vividus/bdd/steps/BddVariableSteps.java:190]: we refer ExamplesTable in many variations in docs, so if you'd like to review the usage of this term you can take care

as for current state of the docs: it's a reference book, it's not an ultimate guide

File: vividus/src/main/java/org/vividus/bdd/steps/BddVariableSteps.java (hunk 3 above)
Comment (valfirst) [reply vividus/src/main/java/org/vividus/bdd/steps/BddVariableSteps.java:198]: nothing weird: we're trying to construct a new object, if it doesn't match the rule, we just throw it away
for simple objects: it could be easy to perform the full check and then construct the object, for complex objects: sometimes the check and the iteration could be of higher cost, than creation of object itself, so some flexibility is required

**Review by uarlouski — APPROVED** [review]

**Review by ikalinin1 — APPROVED** [review]
