### PR TITLE
[plugin-native-app] Fix status bar calculation for android tv

### LINKED ISSUE #2007: [AndroidTV] Unable to establish baseline for android tv
VIVIDUS: 0.3.9-SNAPSHOT

```shell
Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Failed to parse status bar information.
Build info: version: '4.0.0-alpha-1', revision: 'd1d3728cae', time: '2019-04-24T13:42:21'
System info: host: '***', ip: 'fe80:0:0:0:c7a:fe51:14f4:e5bb%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.6', java.version: '16.0.2'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities {app: .., appPackage: *** appiumVersion: 1.20.2, automationName: UiAutomator2, databaseEnabled: false, desired: {app: ..., appiumVersion: 1.20.2, automationName: UiAutomator2, platformName: android, udid: ***}, deviceApiLevel: 28, deviceManufacturer: Xiaomi, deviceModel: MIBOX4, deviceName: 18554282254222, deviceScreenDensity: 320, deviceScreenSize: 1920x1080, deviceUDID: ****, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: true, pixelRatio: 2, platform: LINUX, platformName: Android, platformVersion: 9, statBarHeight: 0, takesScreenshot: true, udid: ****, viewportRect: {height: 1080, left: 0, top: 0, width: 1920}, warnings: {}, webStorageEnabled: false}
Session ID: 909df899-b70d-4de8-95fd-186d1fad4a47
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:190) ~[selenium-remote-driver-4.0.0-alpha-1.jar:?]
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:124) ~[selenium-remote-driver-4.0.0-alpha-1.jar:?]
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:51) ~[selenium-remote-driver-4.0.0-alpha-1.jar:?]
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:161) ~[selenium-remote-driver-4.0.0-alpha-1.jar:?]
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239) ~[java-client-7.1.0.jar:?]
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:577) ~[selenium-remote-driver-4.0.0-alpha-1.jar:?]
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:634) ~[selenium-remote-driver-4.0.0-alpha-1.jar:?]
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41) ~[java-client-7.1.0.jar:?]
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1) ~[java-client-7.1.0.jar:?]
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1) ~[java-client-7.1.0.jar:?]
	at io.appium.java_client.CommandExecutionHelper.execute(CommandExecutionHelper.java:27) ~[java-client-7.1.0.jar:?]
	at org.vividus.selenium.mobileapp.MobileAppWebDriverManager.getAndroidStatusBar(MobileAppWebDriverManager.java:62) ~[vividus-plugin-mobile-app-0.3.9-SNAPSHOT.jar:0.3.9-SNAPSHOT]
	at org.vividus.selenium.mobileapp.MobileAppWebDriverManager.getStatusBarSize(MobileAppWebDriverManager.java:55) ~[vividus-plugin-mobile-app-0.3.9-SNAPSHOT.jar:0.3.9-SNAPSHOT]
	at org.vividus.selenium.mobileapp.screenshot.MobileAppAshotFactory.create(MobileAppAshotFactory.java:56) ~[vividus-plugin-mobile-app-0.3.9-SNAPSHOT.jar:0.3.9-SNAPSHOT]
	at org.vividus.selenium.screenshot.AbstractScreenshotTaker.crateAshot(AbstractScreenshotTaker.java:124) ~[vividus-extension-selenium-0.3.9-SNAPSHOT.jar:0.3.9-SNAPSHOT]
	at org.vividus.selenium.screenshot.AbstractScreenshotTaker.takeAshotScreenshot(AbstractScreenshotTaker.java:109) ~[vividus-extension-selenium-0.3.9-SNAPSHOT.jar:0.3.9-SNAPSHOT]
	at org.vividus.visual.screenshot.AshotScreenshotProvider.take(AshotScreenshotProvider.java:64) ~[vividus-extension-visual-testing-0.3.9-SNAPSHOT.jar:0.3.9-SNAPSHOT]
	at org.vividus.visual.engine.VisualTestingEngine.getCheckpointScreenshot(VisualTestingEngine.java:73) ~[vividus-plugin-visual-0.3.9-SNAPSHOT.jar:0.3.9-SNAPSHOT]
	at org.vividus.visual.engine.VisualTestingEngine.establish(VisualTestingEngine.java:65) ~[vividus-plugin-visual-0.3.9-SNAPSHOT.jar:0.3.9-SNAPSHOT]
	at org.vividus.visual.VisualSteps.lambda$performVisualAction$2(VisualSteps.java:98) ~[vividus-plugin-visual-0.3.9-SNAPSHOT.jar:0.3.9-SNAPSHOT]
	at org.vividus.visual.bdd.AbstractVisualSteps.execute(AbstractVisualSteps.java:53) ~[vividus-extension-visual-testing-0.3.9-SNAPSHOT.jar:0.3.9-SNAPSHOT]
	at org.vividus.visual.VisualSteps.performVisualAction(VisualSteps.java:94) ~[vividus-plugin-visual-0.3.9-SNAPSHOT.jar:0.3.9-SNAPSHOT]
	at org.vividus.visual.VisualSteps.runVisualTests(VisualSteps.java:73) ~[vividus-plugin-visual-0.3.9-SNAPSHOT.jar:0.3.9-SNAPSHOT]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.jbehave.core.steps.StepCreator$ParametrisedStep.perform(StepCreator.java:861) ~[jbehave-core-5.0.0-alpha.13.jar:?]
	... 18 more
```

### PR DESCRIPTION
**Pull request by ikalinin1**
fixes #2007

### CODE REVIEW

File: vividus-plugin-mobile-app/src/main/java/org/vividus/selenium/mobileapp/MobileAppWebDriverManager.java [hunk 1]
```diff
@@ -52,21 +53,28 @@ public MobileAppWebDriverManager(IWebDriverProvider webDriverProvider,
...
+            Map<String, Map<String, Object>>  systemBars = CommandExecutionHelper.execute(details,
+                    AndroidMobileCommandHelper.getSystemBarsCommand());
+            return Optional.ofNullable(systemBars)
+                           .map(b -> b.get("statusBar"))
+                           .map(sb -> sb.get("height"))
+                           .map(Long.class::cast)
+                           .map(Long::intValue)
+                           .orElse(0);
+        }
+        catch (WebDriverException e)
```
Comment (valfirst) [inline vividus-plugin-mobile-app/src/main/java/org/vividus/selenium/mobileapp/MobileAppWebDriverManager.java:74]: do we know/understand the root cause?

Comment (ikalinin1) [reply vividus-plugin-mobile-app/src/main/java/org/vividus/selenium/mobileapp/MobileAppWebDriverManager.java:74]: I was not able to find the issue in Appium. We met the issue for android tv (I am not sure if any of the android TVs could have a status bar at all, but from the session caps I saw that statBarHeight appears in session details, and to be on the safe side I added fall-back code to rely on this capability even if in our case it is 0)

Comment (valfirst) [reply vividus-plugin-mobile-app/src/main/java/org/vividus/selenium/mobileapp/MobileAppWebDriverManager.java:74]: please add this comment to `catch` block

**Review by uarlouski — APPROVED** [review]

**Review by valfirst — APPROVED** [review]
