### PR TITLE
Fixes

### LINKED ISSUE #255: ScrollTo method doesn't work in Microsoft EDGE
**Describe the bug**
When the steps below are performed in EDGE browser, the following error occurs: Object doesn't support property or method 'scrollTo'.
When I change context to an element by By.cssSelector(div[du-scroll-container])
When I scroll to the end of the context
or
When I perform javascript 'document.querySelector("div[du-scroll-container]").scrollTop(0, 4800); return 0;' and save result to the 'STORY' variable 'scrollVar'

**To Reproduce**
Given I am on a page with the URL 'https://yandex.by/'
When I change context to an element by By.cssSelector(div[du-scroll-container])
When I scroll to the end of the context
**or**
Given I am on a page with the URL 'https://yandex.by/'
When I perform javascript 'document.querySelector("div[du-scroll-container]").scrollTo(0, 4800); return 0;' and save result to the 'STORY' variable 'scrollVar'

**Expected behavior**
The page is scrolled to the bottom.

**Artifacts**

[Edge scroll allure.zip](https://github.com/vividus-framework/vividus/files/4053186/Edge.scroll.allure.zip)

**Execution environment (please complete the following information):**
 - Vividus version: ['0.2.0-SNAPSHOT']
 - Build info: version: '4.0.0-alpha-1', revision: 'd1d3728cae', time: '2019-04-24T13:42:21' java.version: '11.0.1' Driver info: org.openqa.selenium.edge.EdgeDriver  

**Desktop Web (if applicable, please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [MicrosoftEdge]
 - Version [44.18362.449.0]

### PR DESCRIPTION
**Pull request by uarlouski**
Fixes #255

Edge doesn't support `scrollTo`: https://caniuse.com/#feat=mdn-api_element_scrollto

### CODE REVIEW

File: vividus-plugin-web-app/src/main/java/org/vividus/ui/web/action/JavascriptActions.java [hunk 1]
```diff
@@ -102,7 +102,7 @@ public void scrollToStartOfPage()
     @Override
     public void scrollToEndOf(WebElement element)
     {
-        executeScript("arguments[0].scrollTo(0, arguments[0].scrollHeight)", element);
+        executeScript("arguments[0].scrollTop = arguments[0].scrollHeight", element);
```
Comment (ikalinin1) [inline vividus-plugin-web-app/src/main/java/org/vividus/ui/web/action/JavascriptActions.java]: Could you please add an integration test
