### PR TITLE
Fix915 : Provide possibility to debug API scenarios

### LINKED ISSUE #915: Provide possibility to debug API scenarios (show screenshot in Allure report when step fails)
Can you please add smth like exisiting selenium.screenshot.debug-directory setting in debug purpose to investigate fails of API scenarios?
We need information what page vividus was focused on the step before fail.
For example we see the following fail in the Allure report:
image-2020-09-09-00-44-42-124

The reason why there is no GET request with event14 in it is that vividus was not focused on the window that was open before that and as a result did not click the element.
Adding additional screenshot on the last performed UI step will really help to find the cause of the fail.

### PR DESCRIPTION
**Pull request by TatianaTochko**
Closes #915 
Provide possibility to debug API scenarios (show screenshot in Allure report when step fails)
Use 
screenshot.on-failure.debug-modes=proxy

### CODE REVIEW

File: vividus-plugin-web-app/src/main/java/org/vividus/proxy/steps/ProxySteps.java [hunk 1]
```diff
@@ -50,6 +51,7 @@
 import org.vividus.ui.web.action.IWebWaitActions;
 
 @SuppressWarnings("PMD.ExcessiveImports")
+@TakeScreenshotOnFailure
```
Comment (ikalinin1) [inline vividus-plugin-web-app/src/main/java/org/vividus/proxy/steps/ProxySteps.java:54]: How this would help to debug proxy steps?

**Review by ikalinin1 — APPROVED** [review]

File: docs/modules/plugins/pages/plugin-web-app.adoc [hunk 2]
```diff
@@ -170,6 +170,10 @@ element xref:parameters:state.adoc[State]
 |Description
 
 include::partial$selenium-properties.adoc[]
+|failure-screenshot-debug-mode
```
Comment (valfirst) [inline docs/modules/plugins/pages/plugin-web-app.adoc:173]: `screenshot.on-failure.debug-modes`?

File: vividus-extension-selenium/src/main/java/org/vividus/bdd/monitor/AbstractScreenshotOnFailureMonitor.java [hunk 3]
```diff
@@ -41,6 +41,8 @@
 
     private static final Logger LOGGER = LoggerFactory.getLogger(AbstractScreenshotOnFailureMonitor.class);
 
+    private static String onlyDebugMode;
```
Comment (valfirst) [inline vividus-extension-selenium/src/main/java/org/vividus/bdd/monitor/AbstractScreenshotOnFailureMonitor.java:44]: `private List<String> debugModes;`

File: vividus-extension-selenium/src/main/java/org/vividus/bdd/monitor/AbstractScreenshotOnFailureMonitor.java [hunk 4]
```diff
@@ -128,4 +144,22 @@ private boolean isScenarioHasNoScreenshotsOnFailureMeta()
                        .map(Scenario::getMeta)
                        .map(m -> m.hasProperty(NO_SCREENSHOT_ON_FAILURE_META_NAME)).orElse(Boolean.FALSE);
     }
+
+    private static boolean isFailureInDebugMode(String modeProperty, String modeAnnotation)
+    {
+        String[] temp = modeProperty.split(", ");
```
Comment (valfirst) [inline vividus-extension-selenium/src/main/java/org/vividus/bdd/monitor/AbstractScreenshotOnFailureMonitor.java:150]: let Spring do its work, it should parse everything automatically

File: vividus-extension-selenium/src/main/java/org/vividus/bdd/monitor/AbstractScreenshotOnFailureMonitor.java [hunk 5]
```diff
@@ -128,4 +144,22 @@ private boolean isScenarioHasNoScreenshotsOnFailureMeta()
...
+        {
+            if (modeAnnotation.contains(mode))
+            {
+                return true;
+            }
+        }
+        return false;
+    }
+
+    public static void setOnlyDebugMode(String onlyDebugMode)
```
Comment (valfirst) [inline vividus-extension-selenium/src/main/java/org/vividus/bdd/monitor/AbstractScreenshotOnFailureMonitor.java:161]: do not use static setters

File: vividus-extension-selenium/src/main/java/org/vividus/bdd/monitor/AbstractScreenshotOnFailureMonitor.java (hunk 3 above)
Comment (valfirst) [inline vividus-extension-selenium/src/main/java/org/vividus/bdd/monitor/AbstractScreenshotOnFailureMonitor.java:44]: also please pay attention it shouldn't be static

**Review by valfirst — CHANGES_REQUESTED** [review]

File: docs/modules/plugins/pages/plugin-web-app.adoc [hunk 6]
```diff
@@ -170,6 +170,10 @@ element xref:parameters:state.adoc[State]
...
+|proxy
+|null
```
[the remark this answers is not in the document]
Comment (TatianaTochko) [reply docs/modules/plugins/pages/plugin-web-app.adoc:175]: Yea, empty property. I'll fix it

File: vividus-extension-selenium/src/main/java/org/vividus/bdd/monitor/AbstractScreenshotOnFailureMonitor.java [hunk 7]
```diff
@@ -128,4 +144,25 @@ private boolean isScenarioHasNoScreenshotsOnFailureMeta()
...
+
+    private boolean isFailureInDebugMode(String modeAnnotation)
+    {
+        if (debugModes == null)
+        {
+            return false;
+        }
+        for (String mode: debugModes)
+        {
+            if (modeAnnotation.contains(mode))
```
Comment (valfirst) [inline vividus-extension-selenium/src/main/java/org/vividus/bdd/monitor/AbstractScreenshotOnFailureMonitor.java:156]: why is so tricky?

File: vividus-extension-selenium/src/main/java/org/vividus/bdd/monitor/AbstractScreenshotOnFailureMonitor.java [hunk 8]
```diff
@@ -98,10 +101,23 @@ public void onAssertionFailure(AssertionFailedEvent event)
...
+            {
+                return true;
+            }
+            else
+            {
+                return isFailureInDebugMode(onlyInDebugMode);
+            }
+        }
+        return method != null && (method.isAnnotationPresent(TakeScreenshotOnFailure.class)
+               || method.getDeclaringClass().isAnnotationPresent(TakeScreenshotOnFailure.class));
```
Comment (valfirst) [inline vividus-extension-selenium/src/main/java/org/vividus/bdd/monitor/AbstractScreenshotOnFailureMonitor.java:120]: consider refactoring to avoid duplicate checks

**Review by valfirst — CHANGES_REQUESTED** [review]

File: vividus-extension-selenium/src/main/java/org/vividus/bdd/monitor/AbstractScreenshotOnFailureMonitor.java [hunk 9]
```diff
@@ -98,10 +101,23 @@ public void onAssertionFailure(AssertionFailedEvent event)
...
+            if (onlyInDebugMode.isEmpty())
+            {
+                return true;
+            }
+            else
+            {
+                return isFailureInDebugMode(onlyInDebugMode);
+            }
+        }
+        return method != null && (method.isAnnotationPresent(TakeScreenshotOnFailure.class)
```
Comment (ikalinin1) [inline vividus-extension-selenium/src/main/java/org/vividus/bdd/monitor/AbstractScreenshotOnFailureMonitor.java:119]: And what is the strategy when I have debugOnly annotation at the class level and on the other hand I have a method that annotated to take screenshots always?

Comment (TatianaTochko) [reply vividus-extension-selenium/src/main/java/org/vividus/bdd/monitor/AbstractScreenshotOnFailureMonitor.java]: Added the ability to add an annotation with debugMode at method level.
Behavior is as follows now:  If debugOnly annotation presents at the class level and I have a method that annotated to take screenshots, screenshot will be appear

**Review by valfirst — CHANGES_REQUESTED** [review]

File: vividus-extension-selenium/src/main/java/org/vividus/bdd/monitor/AbstractScreenshotOnFailureMonitor.java [hunk 10]
```diff
@@ -98,10 +101,27 @@ public void onAssertionFailure(AssertionFailedEvent event)
...
+                                                 : method.getDeclaringClass()
+                                                 .getAnnotation(TakeScreenshotOnFailure.class);
+            String debugModeProperty = annotation.onlyInDebugMode();
+            if (!debugModeProperty.isEmpty())
+            {
+                if (debugModes == null)
+                {
+                    return false;
+                }
+                return debugModes.stream().anyMatch(s -> debugModeProperty.contains(s));
```
[the remark this answers is not in the document]
Comment (TatianaTochko) [reply vividus-extension-selenium/src/main/java/org/vividus/bdd/monitor/AbstractScreenshotOnFailureMonitor.java:121]: For using in annotation smth like @TakeScreenshotOnFailure(onlyInDebugMode = "proxy, ui, .., ")

File: vividus-extension-selenium/src/main/java/org/vividus/bdd/monitor/AbstractScreenshotOnFailureMonitor.java [hunk 11]
```diff
@@ -98,10 +101,27 @@ public void onAssertionFailure(AssertionFailedEvent event)
...
-        return method != null && (method.isAnnotationPresent(TakeScreenshotOnFailure.class) || method
-                .getDeclaringClass().isAnnotationPresent(TakeScreenshotOnFailure.class));
+        boolean isAnnotationPresent = method != null && (method.isAnnotationPresent(TakeScreenshotOnFailure.class)
+                                     || method.getDeclaringClass().isAnnotationPresent(TakeScreenshotOnFailure.class));
+        if (isAnnotationPresent)
+        {
+            TakeScreenshotOnFailure annotation = method.isAnnotationPresent(TakeScreenshotOnFailure.class)
+                                                 ? method.getAnnotation(TakeScreenshotOnFailure.class)
+                                                 : method.getDeclaringClass()
+                                                 .getAnnotation(TakeScreenshotOnFailure.class);
```
[the remark this answers is not in the document]
Comment (TatianaTochko) [reply vividus-extension-selenium/src/main/java/org/vividus/bdd/monitor/AbstractScreenshotOnFailureMonitor.java:113]: In the first check we verify if the annotation present (without checks where it is: in class or method level) In the second we verify if the annotation in method level, we get annotation from method, else from class

[the remark this answers is not in the document]
Comment (TatianaTochko) [reply vividus-extension-selenium/src/main/java/org/vividus/bdd/monitor/AbstractScreenshotOnFailureMonitor.java:113]: In the first check we verify if the annotation present (without checks where it is: in class or method level) In the second we verify if the annotation in method level, we get annotation from method, else from class

File: vividus-extension-selenium/src/main/java/org/vividus/bdd/monitor/AbstractScreenshotOnFailureMonitor.java (hunk 10 above)
[the remark this answers is not in the document]
Comment (valfirst) [reply vividus-extension-selenium/src/main/java/org/vividus/bdd/monitor/AbstractScreenshotOnFailureMonitor.java:121]: `onlyInDebugMode` should contain a single debug mode, if collection is needed, it will be implemented separately, and collection will be used as an annotation field

**Review by valfirst — CHANGES_REQUESTED** [review]

File: vividus-extension-selenium/src/main/java/org/vividus/bdd/monitor/AbstractScreenshotOnFailureMonitor.java [hunk 12]
```diff
@@ -98,10 +101,35 @@ public void onAssertionFailure(AssertionFailedEvent event)
...
+        if (isAnnotationPresent)
+        {
+            String debugModeProperty = annotation.onlyInDebugMode();
+            if (!debugModeProperty.isEmpty())
+            {
+                if (debugModes == null)
+                {
+                    return false;
+                }
+                return debugModes.stream().anyMatch(s -> debugModeProperty.equals(s));
```
Comment (valfirst) [inline vividus-extension-selenium/src/main/java/org/vividus/bdd/monitor/AbstractScreenshotOnFailureMonitor.java:129]: `return debugModes == null || debugModes.stream().anyMatch(debugModeProperty::equals);`

**Review by valfirst — CHANGES_REQUESTED** [review]

File: vividus-extension-selenium/src/main/java/org/vividus/bdd/monitor/AbstractScreenshotOnFailureMonitor.java [hunk 13]
```diff
@@ -98,10 +101,30 @@ public void onAssertionFailure(AssertionFailedEvent event)
...
+        boolean annotationPresent = annotation != null;
+        if (annotationPresent)
+        {
+            String debugModeProperty = annotation.onlyInDebugMode();
+            if (!debugModeProperty.isEmpty())
+            {
+                return debugModes == null || debugModes.stream().anyMatch(debugModeProperty::equals);
+            }
+        }
+        return annotationPresent;
```
Comment (valfirst) [inline vividus-extension-selenium/src/main/java/org/vividus/bdd/monitor/AbstractScreenshotOnFailureMonitor.java:127]:
```java
if (method != null)
{
    AnnotatedElement annotatedElement = method.isAnnotationPresent(TakeScreenshotOnFailure.class) ? method
            : method.getDeclaringClass();
    TakeScreenshotOnFailure annotation = annotatedElement.getAnnotation(TakeScreenshotOnFailure.class);
    if (annotation != null)
    {
        String debugModeProperty = annotation.onlyInDebugMode();
        return debugModeProperty.isEmpty() || debugModes == null || debugModes.stream().anyMatch(
                debugModeProperty::equals);
    }
}
return false;
```

**Review by valfirst — CHANGES_REQUESTED** [review]

**Review by valfirst — APPROVED** [review]

**Review by uarlouski — APPROVED** [review]

**Review by ikalinin1 — APPROVED** [review]
