### PR TITLE
[plugin-web-app-to-rest-api] Remove `IllegalStateException` from http redirects provider

### LINKED ISSUE #4360: Remove unsafe `IllegalStateException` from `HttpRedirectsProvider`
Remove unsafe `IllegalStateException` from [HttpRedirectsProvider](https://github.com/vividus-framework/vividus/blob/master/vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/http/HttpRedirectsProvider.java).

Remove exception handling from method calling classes (like `AbstractFetchingUrlsTableTransformer`)

### PR DESCRIPTION
**Pull request by draker94**
Closes #4360

### CODE REVIEW

File: vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/http/HttpRedirectsProvider.java [hunk 1]
```diff
@@ -32,20 +34,20 @@ public class HttpRedirectsProvider
...
-            httpClient.doHttpHead(from, httpContext).verifyStatusCodeInRange(HttpStatus.SC_OK,
-                    HttpStatus.SC_MULTI_STATUS);
-            return httpContext.getRedirectLocations().getAll();
+            response = httpClient.doHttpHead(from, httpContext);
         }
-        catch (IOException | ExternalServiceException e)
+        catch (IOException e)
         {
             String exceptionMsg;
             if (e.getCause() instanceof CircularRedirectException)
```
Comment (uarlouski) [inline vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/http/HttpRedirectsProvider.java:53]: are you sure that CircularRedirectException can be cause of IOException?

Comment (draker94) [reply vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/http/HttpRedirectsProvider.java:53]: > are you sure that CircularRedirectException can be cause of IOException?

As `HttpException` it should set as cause of `ClientProtocolException` (`IOException`)
https://github.com/apache/httpcomponents-client/blob/master/httpclient5/src/main/java/org/apache/hc/client5/http/impl/classic/CloseableHttpClient.java#L261

**Review by valfirst — APPROVED** [review]

File: vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/http/HttpRedirectsProvider.java (hunk 1 above)
Comment (draker94) [reply vividus-plugin-web-app-to-rest-api/src/main/java/org/vividus/http/HttpRedirectsProvider.java:53]: In fact, the exception should be wrapped even here
https://github.com/apache/httpcomponents-client/blob/master/httpclient5/src/main/java/org/apache/hc/client5/http/impl/classic/InternalHttpClient.java#L173

**Review by uarlouski — APPROVED** [review]
