### PR TITLE
[plugin-web-app] Add possibility to override browser's proxy host

### LINKED ISSUE #1149: Add possibility to override host and port for proxy
**Describe the bug**
Add possibility to override host and port when using proxy

**To Reproduce**
1. Override proxy and port using properties 'vividus.proxy.host' and vividus.proxy.port' in properties file
2. Run story with meta tag @proxy
3. Verify that override value of host and port are used

**Expected behavior**
Host and port are not override

**Artifacts**
If applicable, add artifacts to help explain your problem:
```
2020-11-13 15:11:28,939 [batch-1-thread-1] INFO  org.littleshoot.proxy.impl.DefaultHttpProxyServer - Starting proxy at address: 0.0.0.0/0.0.0.0:0
2020-11-13 15:11:28,973 [batch-1-thread-1] INFO  org.littleshoot.proxy.impl.DefaultHttpProxyServer - Proxy listening with TCP transport
2020-11-13 15:11:29,064 [batch-1-thread-1] INFO  org.littleshoot.proxy.impl.DefaultHttpProxyServer - Proxy started at address: /0:0:0:0:0:0:0:0:44024
```
command that was used for execution
./gradlew spotlessApply runStories  -Pvividus.proxy.host=1.1.1.1

**Execution environment (please complete the following information):**
 - vividus: 0.2.9-SNAPSHOT

### PR DESCRIPTION
**Pull request by ikalinin1**
Closes #1149

### CODE REVIEW

File: vividus-extension-selenium/src/main/java/org/vividus/proxy/Proxy.java [hunk 1]
```diff
@@ -112,7 +115,19 @@ public void clearRequestFilters()
     @Override
     public org.openqa.selenium.Proxy createSeleniumProxy()
     {
-        return ClientUtil.createSeleniumProxy(proxyServer, InetAddress.getLoopbackAddress());
+        return Optional.ofNullable(proxyHost)
+                       .map(this::createSeleniumProxy)
+                       .orElseGet(() -> ClientUtil.createSeleniumProxy(proxyServer, InetAddress.getLoopbackAddress()));
+    }
+
+    private org.openqa.selenium.Proxy createSeleniumProxy(String hostName)
```
Comment (uarlouski) [inline vividus-extension-selenium/src/main/java/org/vividus/proxy/Proxy.java:123]:
```
String proxyAddress = hostName + ':' + proxyServer.getPort();
return new org.openqa.selenium.Proxy().setHttpProxy(proxyAddress)
                                                                    .setSslProxy(proxyAddress);
```
maybe

Comment (valfirst) [inline vividus-extension-selenium/src/main/java/org/vividus/proxy/Proxy.java:123]: `com.browserup.bup.client.ClientUtil#createSeleniumProxy(com.browserup.bup.BrowserUpProxy, java.net.InetAddress)` ?

File: docs/modules/plugins/pages/plugin-web-app.adoc [hunk 2]
```diff
@@ -190,6 +190,26 @@ include::partial$selenium-properties.adoc[]
...
+|any host name resolving on the machine
+|empty
+|Overrides the host which will be used by proxy
+
+|proxy.ports
+|10000-10005
+|empty
+|Defines ports range which could be used for proxy
+
+|selenium.proxy.host
```
Comment (valfirst) [inline docs/modules/plugins/pages/plugin-web-app.adoc:209]: `selenium.proxy.host` -> `proxy.connectable-host` ? that's a naming from BrowserUp proxy

> connectableAddress the network address the Selenium Proxy will use to reach this BrowserUpProxy instance

**Review by valfirst — CHANGES_REQUESTED** [review]

File: vividus-extension-selenium/src/main/java/org/vividus/proxy/Proxy.java (hunk 1 above)
Comment (ikalinin1) [reply vividus-extension-selenium/src/main/java/org/vividus/proxy/Proxy.java:123]: InetAddress will resolve it, and there is no guarantee that it could be resolved from the machine where the tests running

Comment (ikalinin1) [reply vividus-extension-selenium/src/main/java/org/vividus/proxy/Proxy.java:123]: Having host.docker.internal it will throw UnknownHostException with a trace:
{code}
Caused by: java.net.UnknownHostException: host.docker.internal: nodename nor servname provided, or not known
	at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:930)
	at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1499)
	at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:849)
	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1489)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1348)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1282)
	at java.base/java.net.InetAddress.getByName(InetAddress.java:1232)
	at org.vividus.proxy.Proxy.createSeleniumProxy(Proxy.java:133)
{code}

Comment (valfirst) [reply vividus-extension-selenium/src/main/java/org/vividus/proxy/Proxy.java:123]: FYI: https://github.com/browserup/browserup-proxy/pull/318

**Review by valfirst — APPROVED** [review]

**Review by uarlouski — APPROVED** [review]
