### PR TITLE
Make baselines folder resolving lazy and cached

### LINKED ISSUE #68: Error when adding visual testing plugin
```
$ ./gradlew build eclipse

2019-09-06 16:38:41,573 [main] ERROR org.vividus.runner.VividusInitializationChecker - org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'visualSteps': Unsatisfied dependency expressed through field 'visualTestingEngine'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'visualTestingEngine': Unsatisfied dependency expressed through field 'baselineRepository'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'fileSystemBaselineRepository' defined in URL [jar:file:/D:/***/.out/caches/modules-2/files-2.1/org.vividus/vividus-plugin-visual/0.1.0-SNAPSHOT/f040643f48b9fe19b27a5c474f160f8a3e53c07/vividus-plugin-visual-0.1.0-SNAPSHOT.jar!/spring.xml]: Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Resource with name /baselines for class org.vividus.visual.engine.FileSystemBaselineRepository is not found
2019-09-06 16:38:41,579 [main] ERROR org.vividus.runner.VividusInitializationChecker - org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'visualTestingEngine': Unsatisfied dependency expressed through field 'baselineRepository'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'fileSystemBaselineRepository' defined in URL [jar:file:/D:/***/.out/caches/modules-2/files-2.1/org.vividus/vividus-plugin-visual/0.1.0-SNAPSHOT/f040643f48b9fe19b27a5c474f160f8a3e53c07/vividus-plugin-visual-0.1.0-SNAPSHOT.jar!/spring.xml]: Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Resource with name /baselines for class org.vividus.visual.engine.FileSystemBaselineRepository is not found
2019-09-06 16:38:41,583 [main] ERROR org.vividus.runner.VividusInitializationChecker - org.springframework.beans.factory.BeanCreationE                               xception: Error creating bean with name 'fileSystemBaselineRepository' defined in URL [jar:file:/D:/***/.out/caches/modules-2/files-2.1/org.vividus/vividus-plugin-visual/0.1.0-SNAPSHOT/f040643f48b9fe19b27a5c474f160f8a3e53c07/vividus-plugin-visual-0.1.0-SNAPSHOT.jar!/spring.xml]: Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Resource with name /baselines for class org.vividus.visual.engine.FileSystemBaselineRepository is not found
2019-09-06 16:38:43,017 [main] WARN  org.apache.tika.parser.SQLite3Parser - org.xerial's sqlite-jdbc is not loaded.
Please provide the jar on your classpath to parse sqlite files.
See tika-parsers/pom.xml for the correct version.
Exception in thread "main" java.lang.RuntimeException: Initialization of beans has been failed
        at org.vividus.runner.VividusInitializationChecker.main(VividusInitializationChecker.java:86)

> Task :testVividusInitialization FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':testVividusInitialization'.
> Process 'command 'C:\Program Files\Java\jdk-11.0.1\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 21s
9 actionable tasks: 3 executed, 6 up-to-date

```

**Workaround:** Adding of /baselines folder in src/main/resources fixes the build and vis plugin added successfully.

**Suggestion:** To fix this baseline folder login inside the framework to avoid issues.

### PR DESCRIPTION
**Pull request by ikalinin1**
closes #68

### CODE REVIEW

File: vividus-plugin-visual/src/main/java/org/vividus/visual/engine/FileSystemBaselineRepository.java [hunk 1]
```diff
@@ -38,22 +41,22 @@
 
     private File baselinesFolder;
 
-    public void init()
-    {
+    private Supplier<File> baselineFolderResolver = Suppliers.memoize(() -> {
```
Comment (uarlouski) [inline vividus-plugin-visual/src/main/java/org/vividus/visual/engine/FileSystemBaselineRepository.java]: final
